src/Root.tsx
src/components/Avatar.tsx
src/components/Button/index.tsx
src/components/dropdown/Dropdown.tsx
src/components/index.ts
src/pages/AvatarPage.tsx

Hi! This PR adds the avatar component 
/closes #3

Avatar component

---

src/components/Card/index.tsx
src/pages/CardPage.tsx

Allows `Card`s to pass `imgAlt` to provide `alt` text to the underlying `<img/>`, when an `imgSrc` has also been provided.
Now, by default, `Card`s with an image will have `alt=""`, which browsers interpret appropriately as [decorative images](https://www.w3.org/WAI/tutorials/images/decorative/).
To add `alt` text to your `Card` with an image:
```js
<Card
imgAlt="Meaningful alt text for an image that is not purely decorative"
imgSrc="https://flowbite.com/docs/images/people/profile-picture-5.jpg"
>
..
</Card>
```
Also renames the existing `Card with image` example to `Card with decorative image` to more clearly indicate `alt` text *should* be provided if the image is *not* purely decorative.

feat(component): Add `imgAlt` attribute to `Card`s 

---

src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/index.tsx
src/pages/AvatarPage.tsx

Allows `Avatar`s to pass `alt` text to the underlying `<img/>`.
Now, by default, `Avatar`s will have `alt=""`, which browsers interpret appropriately as
[decorative images](https://www.w3.org/WAI/tutorials/images/decorative/).
To add `alt` text to your `Avatar`:
```js
<AvatarComponent
alt="Default avatar with alt text"
img="https://flowbite.com/docs/images/people/profile-picture-5.jpg"
/>
```

feat(component): Add `alt` attribute to `Avatar`s

---

src/components/Modal/index.tsx

Use createPortal to render modals

---

src/components/Avatar/AvatarGroup.tsx
src/components/Avatar/AvatarGroupCounter.tsx
src/components/Avatar/index.tsx
src/components/Button/ButtonGroup.tsx
src/components/Button/index.tsx

Adds `displayName` fields to compound components.
This is essential for the syntax highlighter we use to display the code needed for each component.
For example, `<ButtonComponent>`, which is invalid, now becomes `<Button>`, which is ready to copy-paste.

fix(component): Add `displayName`s for syntax highlighter, resolving #70

---

.storybook/preview.js
package.json
src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/index.tsx
yarn.lock

[Floating UI]() is the next evolution of [Popper](). 
We currently have a strange bug on Chromium causing `Dropdown`s/`Tooltip`s to be  misaligned with their target. ~~This upgrade happens to resolve #57, as a bonus!~~
Because `Tooltip` is used by `Dropdown`, both components have been upgraded.
There are no breaking changes to the API.

feat(build): Upgrade `@popperjs/*` to `@floating-ui/react-*`

---

src/docs/pages/SidebarPage.tsx
src/docs/routes.tsx
src/lib/components/Sidebar/Sidebar.stories.tsx

Adds the following examples for `Sidebar`s:
~~The following can't be finished yet, because the
component needs work:~~
Once #72 is accepted I can finalize this PR. 
This resolves #53.
Also adds Storybook stories for Sidebar, resolving #56.

feat(route): Add `Sidebar` examples page & stories, resolving #53 #56

---

README.md
src/docs/pages/FormsPage.tsx

We don't use `HashRouter` anymore, so the links no longer begin with `#`. Also adds anchors to the `Forms` page for each of the components listed (radio, checkbox, and so forth).
None.
None.

fix(docs): Update `README` Components links to new URL pattern

---

README.md

chore(docs): Add `Footer`, `Tabs` links to `flowbite-react.com` in `README`

---

src/docs/pages/BreadcrumbPage.tsx
src/lib/components/Breadcrumb/Breadcrumb.spec.tsx
src/lib/components/Breadcrumb/Breadcrumb.stories.tsx
src/lib/components/Breadcrumb/BreadcrumbItem.tsx
src/lib/components/Breadcrumb/index.tsx

This is a substantial API change. Previously, `Breadcrumb`s looked like:
```js
<Breadcrumb
items={[
{
href: '/breadcrumb',
icon: HiHome,
label: 'Home'
},
{
href: '/breadcrumb',
label: 'Projects'
},
{
label: 'Flowbite React'
}
]}
/>
```
Now, you can write instead:
```js
<Breadcrumb>
<Breadcrumb.Item href="#" icon={HiHome}>
Home
</Breadcrumb.Item>
<Breadcrumb.Item href="#">Projects</Breadcrumb.Item>
<Breadcrumb.Item icon={HiHome}>Flowbite React</Breadcrumb.Item>
</Breadcrumb>
```

feature(component): Rewrite Breadcrumb in composable form

---

src/docs/pages/PaginationPage.tsx
src/lib/components/Pagination/Pagination.spec.tsx
src/lib/components/Pagination/Pagination.stories.tsx
src/lib/components/Pagination/index.tsx
src/lib/helpers/range.ts

`Pagination` has a new API:
```js
<Pagination
currentPage={1}
displayFormat="pagination"
onPageChange={onPageChange}
totalPages={100}
/>
```
```js
<Pagination
currentPage={1}
layout="pagination"
onPageChange={onPageChange}
totalPages={100}
/>
```

test(component): Add unit tests for `Pagination`

---

src/lib/components/Tab/index.tsx

The tab items buttons should have a type of button. In case the tabs are used inside a form element, Clicking tabs won't submit the form.

set tab item button type to "button"

---

src/lib/components/Carousel/index.tsx
src/lib/components/Flowbite/ThemeContext.tsx
src/lib/components/Flowbite/index.tsx
src/lib/components/Modal/index.tsx
src/lib/helpers/window-exists.ts

fix(component): Check for `window` in components

---

src/docs/pages/FormsPage.tsx
src/lib/components/FormControls/Checkbox.spec.tsx
src/lib/components/FormControls/FileInput.spec.tsx
src/lib/components/FormControls/Label.spec.tsx
src/lib/components/FormControls/Radio.spec.tsx
src/lib/components/FormControls/Select.spec.tsx
src/lib/components/FormControls/TextInput.spec.tsx
src/lib/components/FormControls/TextInput.stories.tsx
src/lib/components/FormControls/Textarea.spec.tsx
src/lib/components/FormControls/ToggleSwitch.spec.tsx
src/lib/components/FormControls/ToggleSwitch.stories.tsx
src/lib/components/FormControls/ToggleSwitch.tsx

`ToggleSwitch` now requires:
- `checked` (`boolean`)
- `onChange` (`(checked: boolean) => void`)
You can now use Tab to navigate into a `ToggleSwitch`, and use Space to toggle its state.
```js
const [state, setState] = useState(false);
return <ToggleSwitch checked={state} label="Enable notifications" onChange={setState} />
```

feature(component): Add keyboard controls to `ToggleSwitch`

---

src/docs/pages/BreadcrumbPage.tsx
src/lib/components/Breadcrumb/Breadcrumb.spec.tsx
src/lib/components/Breadcrumb/Breadcrumb.stories.tsx
src/lib/components/Breadcrumb/index.tsx

`Breadcrumb` is uncallable right now in the standard convention:
```js
import {Breadcrumb} from "flowbite-react";
```
Since I `export default`'d. This changes that to a named export so the module can be imported like above.

fix(component): Remove default export from `Breadcrumb`

---

src/docs/pages/ThemePage.tsx
src/lib/components/Alert/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/components/Flowbite/ThemeContext.tsx
src/lib/components/Flowbite/index.tsx
src/lib/theme/default.ts

feature(component): Rewrite `Alert`s to use themes, resolves #126

---

src/docs/pages/AlertsPage.tsx
src/lib/components/Alert/Alert.spec.tsx
src/lib/components/Alert/Alert.stories.tsx

fix: Replace old colors on `Alerts` page & stories

---

src/docs/pages/BadgesPage.tsx
src/lib/components/Badge/Badge.spec.tsx
src/lib/components/Badge/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/theme/default.ts

`Badge`s can now be customized using `<Flowbite theme={..}>`.
```js
badge: {
base: string;
color: Colors;
href: string;
icon: {
disabled: string;
enabled: string;
size: BadgeSizes;
};
size: BadgeSizes;
};
```
- `badge.color` will respect any additional colors you provide, e.g., `<Badge color="primary" />`
- `badge.size` will respect any additional sizes you provide, e.g., `<Badge size="xxl" .../>`
- `badge.icon.size` can also be scaled as needed

feature(component): Rewrite `Badge` to use themes, resolves #128

---

src/lib/components/Breadcrumb/Breadcrumb.spec.tsx
src/lib/components/Breadcrumb/BreadcrumbItem.tsx
src/lib/components/Breadcrumb/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/theme/default.ts

`Breadcrumb`s can now be customized using `<Flowbite theme={..}>`.
```js
breadcrumb: {
item: {
base: string;
chevron: string;
href: {
off: string;
on: string;
};
icon: string;
};
list: string;
};
```

feature(component): Rewrite `Breadcrumb`s to use themes, resolves #129

---

src/docs/pages/SidebarPage.tsx
src/lib/components/Accordion/Accordion.spec.tsx
src/lib/components/Accordion/AccordionContent.tsx
src/lib/components/Accordion/AccordionPanel.tsx
src/lib/components/Accordion/AccordionTitle.tsx
src/lib/components/Accordion/index.tsx
src/lib/components/Alert/index.tsx
src/lib/components/Avatar/Avatar.spec.tsx
src/lib/components/Avatar/index.tsx
src/lib/components/Badge/Badge.spec.tsx
src/lib/components/Badge/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/components/Sidebar/Sidebar.stories.tsx
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/components/Timeline/TimelineTitle.tsx
src/lib/theme/default.ts

`Accordion`s can now be customized using `<Flowbite theme={..}>`.
```js
accordion: {
base: string;
content: {
base: string;
};
flush: {
off: string;
on: string;
};
title: {
arrow: {
base: string;
open: string;
};
base: string;
flush: {
off: string;
on: string;
};
open: {
off: string;
on: string;
};
};
};
```

feature(component): Rewrite `Accordion` to use `FlowbiteTheme`, resolves #125

---

src/docs/pages/CardPage.tsx
src/docs/pages/DemoPage.tsx
src/lib/components/Card/Card.spec.tsx
src/lib/components/Card/Card.stories.tsx
src/lib/components/Card/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/theme/default.ts

`Card`s can now be customized with `<Flowbite theme={..}>`.
```js
card: {
base: 'flex rounded-lg border border-gray-200 bg-white shadow-md dark:border-gray-700 dark:bg-gray-800',
children: 'flex h-full flex-col justify-center gap-4 p-6',
horizontal: {
off: 'flex-col',
on: 'flex-col md:max-w-xl md:flex-row',
},
img: {
base: '',
horizontal: {
off: 'rounded-t-lg',
on: 'h-96 w-full rounded-t-lg object-cover md:h-auto md:w-48 md:rounded-none md:rounded-l-lg',
},
},
},
```

feature(component): Rewrite `Card`s to use themes, resolves #131

---

src/docs/pages/SpinnersPage.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/components/Spinner/Spinner.spec.tsx
src/lib/components/Spinner/Spinner.stories.tsx
src/lib/components/Spinner/index.tsx
src/lib/theme/default.ts

`Spinner`s can now be customized with `<Flowbite theme={..}>`.
```js
spinner: {
base: 'inline animate-spin text-gray-200',
color: {
failure: 'fill-red-600',
gray: 'fill-gray-600',
info: 'fill-blue-600',
pink: 'fill-pink-600',
purple: 'fill-purple-600',
success: 'fill-green-500',
warning: 'fill-yellow-400',
},
light: {
off: {
base: 'dark:text-gray-600',
color: {
failure: '',
gray: 'dark:fill-gray-300',
info: '',
pink: '',
purple: '',
success: '',
warning: '',
},
},
on: {
base: '',
color: {
failure: '',
gray: '',
info: '',
pink: '',
purple: '',
success: '',
warning: '',
},
},
},
size: {
xs: 'w-3 h-3',
sm: 'w-4 h-4',
md: 'w-6 h-6',
lg: 'w-8 h-8',
xl: 'w-10 h-10',
},
},
```

feature(component): Rewrite `Spinner`s to use themes, resolves #144

---

src/docs/pages/SidebarPage.tsx
src/lib/components/Sidebar/Sidebar.spec.tsx
src/lib/components/Sidebar/Sidebar.stories.tsx
src/lib/components/Sidebar/SidebarCTA.tsx
src/lib/components/Sidebar/SidebarCollapse.tsx
src/lib/components/Sidebar/SidebarContext.tsx
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/components/Sidebar/SidebarItemContext.tsx
src/lib/components/Sidebar/SidebarItemGroup.tsx
src/lib/components/Sidebar/SidebarLogo.tsx
src/lib/components/Sidebar/index.tsx

feature(component): Allow `Sidebar`s to hide completely, resolves #81

---

src/docs/pages/AccordionPage.tsx
src/lib/components/Accordion/Accordion.spec.tsx
src/lib/components/Accordion/Accordion.stories.tsx
src/lib/components/Accordion/AccordionContent.tsx
src/lib/components/Accordion/AccordionPanel.tsx
src/lib/components/Accordion/AccordionPanelContext.tsx
src/lib/components/Accordion/AccordionTitle.tsx
src/lib/components/Accordion/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/theme/default.ts

`Accordion`s used to let more than one `Accordion.Panel` be open at once. Now, only the most recently clicked panel will be open.
To override this behavior, specify `<Accordion alwaysOpen>`.
See the [Flowbite Accordion docs](https://flowbite.com/docs/components/accordion/) - notably, the `Default accordion` and `Always open` examples

feature(component): Change `Accordion`s to close inactive panels, resolves #159

---

src/lib/components/Carousel/Carousel.stories.tsx
src/lib/components/Carousel/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/theme/default.ts

`Carousel`s can now be customized using `<Flowbite theme={..}>`.
```js
carousel: {
base: 'relative w-full',
indicators: {
active: {
off: 'bg-white/50 hover:bg-white dark:bg-gray-800/50 dark:hover:bg-gray-800',
on: 'bg-white dark:bg-gray-800',
},
base: 'h-3 w-3 rounded-full',
wrapper: 'absolute bottom-5 left-1/2 flex -translate-x-1/2 space-x-3',
},
item: {
base: 'absolute top-1/2 left-1/2 block w-full -translate-x-1/2 -translate-y-1/2',
wrapper: 'w-full flex-shrink-0 transform cursor-grab snap-center',
},
leftControl: 'absolute top-0 left-0 flex h-full items-center justify-center px-4 focus:outline-none',
rightControl: 'absolute top-0 right-0 flex h-full items-center justify-center px-4 focus:outline-none',
scrollContainer: {
base: 'flex h-56 snap-mandatory overflow-y-hidden …
```

feature(component): Rewrite `Carousel`s to use themes, resolves #168, #132

---

src/docs/pages/ButtonGroupPage.tsx
src/docs/pages/ButtonsPage.tsx
src/lib/components/Accordion/AccordionTitle.tsx
src/lib/components/Badge/index.tsx
src/lib/components/Button/Button.spec.tsx
src/lib/components/Button/ButtonGroup.spec.tsx
src/lib/components/Button/ButtonGroup.tsx
src/lib/components/Button/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/components/Sidebar/SidebarCTA.tsx
src/lib/components/Sidebar/SidebarCollapse.tsx
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/components/Timeline/TimelineTitle.tsx
src/lib/helpers/mergeDeep.spec.ts
src/lib/theme/default.ts

`Button`s and `Button.Group`s can now be customized using `<Flowbite theme={..}>`.
```js
button: {
base: 'group flex h-min w-fit items-center justify-center p-0.5 text-center font-medium focus:z-10',
color: {
dark: 'text-white bg-gray-800 border border-transparent hover:bg-gray-900 focus:ring-4 focus:ring-gray-300 disabled:hover:bg-gray-800 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-800 dark:border-gray-700 dark:disabled:hover:bg-gray-800',
failure:
'text-white bg-red-700 border border-transparent hover:bg-red-800 focus:ring-4 focus:ring-red-300 disabled:hover:bg-red-800 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 dark:disabled:hover:bg-red-600',
gray: 'text-gray-900 bg-white border border-gray-200 hover:bg-gray-100 hover:text-blue-700 …
```

feature(component): Rewrite `Button`s to use themes, resolves #130

---

README.md

`Timeline` is finished now, so it no longer needs the under construction indicator.
Also updates link to point to `flowbite-react.com/timeline`

chore(docs): Update `Timeline` in `README`

---

src/lib/components/Accordion/AccordionTitle.tsx
src/lib/components/Flowbite/FlowbiteTheme.d.ts
src/lib/theme/default.ts

The heading inside `Accordion.Title` needs to be
able to be customized.
```js
theme: {
accordion: {
title: {
heading: 'something'
}
}
}
```

feat(component): Add `Accordion.Title` theme for heading

---

package.json
src/lib/components/Flowbite/index.tsx
src/lib/components/FormControls/ToggleSwitch.tsx
src/lib/components/Progress/index.tsx
src/lib/components/Sidebar/SidebarCollapse.tsx
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/components/Sidebar/SidebarLogo.tsx
src/lib/components/Tab/index.tsx
src/lib/components/Tooltip/index.tsx
yarn.lock

For users running Flowbite in a serverless environment like Cloudflare Workers, Node libraries like `crypto` are unavailable.
Fortunately, React added a hook that serves the exact purpose we need: [`useId()`](https://reactjs.org/blog/2022/03/29/react-v18.html#useid).
None.

fix: `nanoid` requires Node `crypto` module

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Rating/RatingAdvanced.tsx
src/lib/components/Rating/RatingContext.tsx
src/lib/components/Rating/RatingStar.tsx
src/lib/components/Rating/index.tsx
src/lib/theme/default.ts

**Rating** can be customized using  **< Flowbite theme={..} >**
```ts
rating: {
base: string;
star: {
sizes: StarSizes;
filled: string;
empty: string;
};
advanced: {
base: string;
label: string;
progress: {
base: string;
fill: string;
label: string;
};
};
};
```
closes #142

feat(component): theme support to rating

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Pagination/index.tsx
src/lib/theme/default.ts

**Pagination** can be customized using  **<Flowbite theme={..}>**
```ts
pagination: {
base: string;
layout: {
table: {
base: string;
span: string;
};
};
pages: {
base: string;
showIcon: string;
previous: {
base: string;
icon: string;
};
next: {
base: string;
icon: string;
};
selector: {
base: string;
active: string;
};
};
};
```
closes #140

feat(component): theme support to pagination

---

src/docs/pages/ModalPage.tsx
src/lib/components/Avatar/index.tsx
src/lib/components/Button/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Modal/Modal.spec.tsx
src/lib/components/Modal/Modal.stories.tsx
src/lib/components/Modal/ModalBody.tsx
src/lib/components/Modal/ModalFooter.tsx
src/lib/components/Modal/ModalHeader.tsx
src/lib/components/Modal/index.tsx
src/lib/components/Spinner/index.tsx
src/lib/theme/default.ts

**Modal** can be customized using  **<Flowbite theme={..}>**
```ts
modal: {
base: string;
show: FlowbiteBoolean;
content: {
base: string;
inner: string;
};
body: {
base: string;
popup: string;
};
header: {
base: string;
popup: string;
title: string;
close: {
base: string;
icon: string;
};
};
```
closes #138

feat(component): theme support to modal

---

src/lib/components/Dropdown/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Tooltip/index.tsx
src/lib/theme/default.ts

**Tooltip** can be customized using  **<Flowbite theme={..}>**
> **Warning**
> This PR introduces an visual issue to `Dropdown` component that will be fixed in a separated task.
```ts
tooltip: {
target: string;
base: string;
animation: string;
hidden: string;
style: {
dark: string;
light: string;
auto: string;
};
content: string;
arrow: {
base: string;
style: {
dark: string;
light: string;
auto: string;
};
placement: string;
};
};
```
closes #147

feat(component): theme support to tooltip

---

src/lib/components/DarkThemeToggle/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/theme/default.ts

**DarkThemeToggle** can be customized using  **<Flowbite theme={..}>**
```ts
darkThemeToggle: {
base: string;
icon: string;
};
```
closes #133

feat(component): theme support to darkthemetoggle

---

src/docs/pages/ButtonGroupPage.tsx
src/docs/pages/ButtonsPage.tsx
src/docs/pages/ModalPage.tsx
src/docs/pages/SidebarPage.tsx
src/docs/pages/SpinnersPage.tsx
src/docs/pages/TimelinePage.tsx
src/docs/pages/ToastPage.tsx
src/lib/components/Button/Button.spec.tsx
src/lib/components/Button/Button.stories.tsx
src/lib/components/Button/ButtonGroup.stories.tsx
src/lib/components/Button/ButtonGroup.tsx
src/lib/components/Button/index.tsx
src/lib/components/Dropdown/index.tsx
src/lib/components/Modal/Modal.spec.tsx
src/lib/components/Modal/Modal.stories.tsx
src/lib/components/Sidebar/Sidebar.stories.tsx
src/lib/components/Spinner/Spinner.stories.tsx

A pretty common use case is to use a button visual style in combination with a link to another page.
However, HTML doesn't support nesting `<a>` inside of `<button>`.
Adding an `onClick` hook to the `<button>` is fine, but that only works with JavaScript enabled. Keep in mind that React SSR apps still render HTML without JavaScript enabled, but without interactive behaviors.
In this case, they will render as an anchor (`<a>`) instead, which is the best scenario for SSR apps.
You can now add an `href` to a `<Button>` to have it serve as an anchor to another page.
None.

feat(component): Allow `Button`s to have `href`

---

src/lib/components/FormControls/Label.spec.tsx
src/lib/components/FormControls/Label.tsx

You can now declare a `<Label />` as a self-closing tag. Instead of `children`, provide `value`:
```js
<Label htmlFor="email" value="Your email" />
```

feat(component): Allow `Label` as self-closing tag, resolves #173

---

src/lib/theme/default.ts

`Breadcrumb.Item`s with no link (`href`) specified have insufficient contrast using the old color.
None.

fix(a11y): Use darker text for `Breadcrumb.Item`s, resolves #102

---

src/docs/pages/ListGroupPage.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/ListGroup/ListGroup.spec.tsx
src/lib/components/ListGroup/ListGroupItem.tsx
src/lib/components/ListGroup/index.tsx
src/lib/theme/default.ts

You can now theme `ListGroup`s with `<Flowbite theme={..}>`:
```js
listGroup: {
base: string;
item: {
active: FlowbiteBoolean;
base: string;
href: FlowbiteBoolean;
icon: string;
};
};
```

feat(component): Use theme in `ListGroup`s, resolves #137

---

src/docs/pages/CardPage.tsx
src/lib/components/Card/Card.spec.tsx
src/lib/components/Card/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/theme/default.ts

`Card`s can now have an `href`:
```js
<Card href="#">
<h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
Noteworthy technology acquisitions 2021
</h5>
<p className="font-normal text-gray-700 dark:text-gray-400">
Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.
</p>
</Card>
```
See the [Flowbite docs on Cards](https://flowbite.com/docs/components/card/#default-card), specifically, the `Default card` example.

fix(component): Allow `Card` to have `href`

---

src/docs/pages/FooterPage.tsx
src/lib/components/Footer/Footer.stories.tsx

There is a typo in the Flowbite React documentation: 
**Gihub** appears but it should be **Github**

Fix: update typo on Footer.Link from Gihub to Github

---

src/lib/theme/default.ts

Slightly tweak the default `Carousel` theme to make slides fill the height specified in `base`, which makes it much easier for users to override.
`Carousel`s now automatically fill the height of their parent.

fix(component): Allow `Carousel`s to fill height, resolves #168

---

src/docs/Root.tsx
src/docs/pages/SidebarPage.tsx
src/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Sidebar/Sidebar.spec.tsx
src/lib/components/Sidebar/SidebarCTA.tsx
src/lib/components/Sidebar/SidebarCollapse.tsx
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/components/Sidebar/SidebarItemGroup.tsx
src/lib/components/Sidebar/SidebarItems.tsx
src/lib/components/Sidebar/SidebarLogo.tsx
src/lib/components/Sidebar/index.tsx
src/lib/theme/default.ts

`Sidebar`s can now be customized via `<Flowbite theme={..}>`.
```js
sidebar: {
base: string;
collapsed: FlowbiteBoolean;
inner: string;
collapse: {
button: string;
icon: {
base: string;
open: FlowbiteBoolean;
};
label: {
base: string;
icon: string;
};
list: string;
};
cta: {
base: string;
color: SidebarCTAColors;
};
item: {
active: FlowbiteBoolean;
base: string;
collapsed: {
insideCollapse: string;
};
content: {
base: string;
collapsed: string;
};
icon: {
base: string;
active: string;
};
};
items: string;
itemGroup: string;
logo: {
base: string;
collapsed: FlowbiteBoolean;
img: string;
};
};
```

feat(component): Use `FlowbiteTheme` in `Sidebar`s, resolves #143

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/HelperText.spec.tsx
src/lib/components/FormControls/HelperText.tsx
src/lib/components/FormControls/index.ts
src/lib/theme/default.ts

This is a new component that will help us with #136. It should remove some code duplication.
```
helperText: {
base: string;
colors: HelperColors;
};
};
```

feat(component): adding helpertext component

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Tab/TabItem.tsx
src/lib/components/Tab/index.tsx
src/lib/theme/default.ts

**Tab** can be customized using  **<Flowbite theme={..} >**
```
tab: {
base: string;
tablist: {
base: string;
styles: TabStyles;
tabitem: {
base: string;
styles: TabStyleItem<TabStyles>;
icon: string;
};
};
tabpanel: string;
};
```

refactor(tab): adding theme support to component

---

src/docs/pages/CardPage.tsx
src/docs/pages/FormsPage.tsx
src/docs/pages/ModalPage.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/Label.tsx
src/lib/components/Modal/Modal.stories.tsx
src/lib/theme/default.ts

**Label** can be customized using  **<Flowbite theme={..} >**
```
label: {
base: string;
colors: LabelColors;
disabled: string;
};
};
```
This is part of the #136

refactor(label): adding theme support to label

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/Radio.tsx
src/lib/theme/default.ts

**Radio** can be customized using  **<Flowbite theme={..} >**
```
radio: {
base: string;
};
};
```
This is part of the #136

refactor(radio): adding theme support to component

---

src/docs/pages/ModalPage.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/Checkbox.tsx
src/lib/components/Modal/Modal.stories.tsx
src/lib/theme/default.ts

**Checkbox** can be customized using  **<Flowbite theme={..} >**
```
checkbox: {
base: string;
};
};
```
This is part of the #136

refactor(checkbox): adding theme support to component

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/ToggleSwitch.tsx
src/lib/theme/default.ts

**ToggleSwitch** can be customized using  **<Flowbite theme={..} >**
```
toggleSwitch: {
base: string;
active: FlowbiteBoolean;
toggle: {
base: string;
checked: FlowbiteBoolean;
};
label: string;
};
};
```
This is part of the #136

refactor(toggleSwitch): adding theme support to component

---

src/docs/pages/CarouselPage.tsx
src/lib/components/Carousel/Carousel.stories.tsx
src/lib/components/Carousel/index.tsx
src/lib/theme/default.ts

This should fix the issue with the `Carousel` component. Now, it respects the size of his parent object, which allows to the user to have more flexibility over the component size and responsiveness.
The `Carousel` must be wrapped with some `div` that must determine its size.
- Brave Browser

fix(carousel): carousel size depends on parent size

---

src/docs/pages/ModalPage.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/FileInput.tsx
src/lib/components/FormControls/HelperText.tsx
src/lib/components/FormControls/TextInput.tsx
src/lib/components/Modal/Modal.stories.tsx
src/lib/theme/default.ts

Adding theme support for `TextInput` and `FileInput`.
It also rewrites the `FileInput` component to decouple it from `FileInput`.
- Remove direct access to `className` property
- Introduce the theme support as in the configuration description:
```js
textInput: {
base: string;
addon: string;
field: {
base: string;
icon: {
base: string;
svg: string;
};
input: {
base: string;
sizes: TextInputSizes;
colors: TextInputColors;
withIcon: FlowbiteBoolean;
withAddon: FlowbiteBoolean;
withShadow: FlowbiteBoolean;
};
};
};
fileInput: {
base: string;
field: {
base: string;
input: {
base: string;
sizes: TextInputSizes;
colors: TextInputColors;
};
};
};
```
- Browser: Brave 1.39.122
- OS: Fedora 36

refactor(inputs): adds theme support to TextInput and FileInput

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/Textarea.tsx
src/lib/theme/default.ts

Adding the theme support to `Textarea` component.
- It remove the direct access to component's `Classname` props
- It introduce the theme support to the component using the configuration:
```js
textarea: {
base: string;
colors: TextareaColors;
withShadow: FlowbiteBoolean;
}
```
- Browser: Brave 1.39.122
- OS: Firefox 36

refactor(textarea): adds theme support to textarea component

---

src/docs/pages/ModalPage.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/FormControls/Select.tsx
src/lib/theme/default.ts

Adds theme support to the `Select` component.
- Removes direct access to `className` props
- Adds the theme support to the component with the following config:
```js
select: {
base: string;
addon: string;
field: {
base: string;
icon: {
base: string;
svg: string;
};
select: {
base: string;
withIcon: FlowbiteBoolean;
withAddon: FlowbiteBoolean;
withShadow: FlowbiteBoolean;
sizes: SelectSizes;
colors: SelectColors;
};
};
};
```
- Browser: Brave 1.39.122
- OS: Fedora 36

refactor(select): adds theme support to select component

---

package.json
src/lib/components/Dropdown/index.tsx
src/lib/components/Floating/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Tooltip/index.tsx
src/lib/helpers/floating.ts
src/lib/theme/default.ts

Adds theme support to `Dropdown` component. It was necessary to do some refactoring at the `Tooltip` and to create a new intermediary component named `Floating` that is being used in both. It isn't the best solution IMHO, but for now it does the job.
Fixes #134
- Dropdown doesn't have direct access to `className` property anymore;
- Dropdown now supports theme:
```
dropdown: {
floating: FlowbiteFloatingTheme;
content: string;
inlineWrapper: string;
arrowIcon: string;
}
```
- Browser: Brave 1.40.107
- OS: Fedora 36

refactor(dropdown): adds theme support to dropdown

---

src/lib/components/ListGroup/ListGroupItem.tsx

`ListGroup.Item`s currently have `type="button"` always,
even though they can be an anchor (`<a>`) element
instead. That's changed now.
Also adds `props` since they weren't being passed
in for some reason.
None.

fix(component): Remove `type="button"` when not a `<button>`

---

src/lib/components/FormControls/Checkbox.tsx
src/lib/components/FormControls/Radio.tsx
src/lib/components/FormControls/Select.tsx
src/lib/components/FormControls/Textarea.tsx

Added ref forwarding to:
-  `Radio` with changes needed at `RadioProps` in order to not break the `Radio.stories.tsx` file.
- `Textarea` with changes needed at  `TextareaProps` in order to not break the `Textarea.stories.tsx` file.
- `Checkbox` with changes needed at  `CheckboxProps` in order to not break the `Checkbox.stories.tsx` file.
The changes for each component are isolated in their own commits. All the changes where made following the same style used for ref forwarding in `TextInput` (and `TextInputProps`).
The startup I work for wants to use this library but for that we need it to work with the [react-hook-form project](https://react-hook-form.com/get-started), which needs ref forwarding.
Lack of ref forwarding on `Radio`, `Checkbox`, and `Textarea` components
Ran …

Added ref forwarding for Radio, Checkbox, and Textarea components

---

src/index.css

Fixed extra scroll vertical scroll bar on some pages which was causing extra scroll. This was solved by adding `overflow: hidden;` to the body to eliminate extra scrolls
Fixes #270 
After adding property `overflow: hidden;` for the body in `index.css`. I tested each and every page to see if  something breaks but everything seems to work fine

fix extra vertical scroll on some pages

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Sidebar/Sidebar.spec.tsx
src/lib/components/Sidebar/Sidebar.stories.tsx
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/components/Sidebar/index.tsx
src/lib/theme/default.ts

fix(component): display text only on Sidebar.Item tooltip

---

src/lib/components/Button/Button.stories.tsx

We can use the default theme to automatically pick up on which colors the `Button` supports by default.
None.

docs(storybook): add color radio options to `Button` storybook

---

src/lib/components/Footer/FooterCopyright.tsx

We shouldn't require this phrase to use the component. Now you can just add "All Rights Reserved" to the `<Footer.Copyright by=""/>` field, if you would like to.
If you are using a `Footer` and `Footer.Copyright` with a copyright statement that needs to include "All Rights Reserved", you will want to add that in now like so:
```js
<Footer.Copyright by="My Company. All Rights Reserved." year={2022} />
```

fix(component): remove "All Rights Reserved" from `<Footer.Copyright>`

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Navbar/index.tsx
src/lib/theme/default.ts

Signed-off-by: chankruze <chankruze@gmail.com>
This is just a fix for a typo in `FlowbiteTheme.d.ts` ass discussed in the discord chat.

fix: typo in navbar theme typedef

---

src/lib/components/FormControls/Checkbox.tsx
src/lib/components/FormControls/Radio.tsx
src/lib/components/FormControls/Select.tsx

There are missing display names on checkbox, radio and select. This causes the following in the docs site:
None
Ran test and build

fix(component): add missing display name for checkbox, radio and select

---

src/docs/Root.tsx
src/lib/components/Navbar/index.tsx
src/lib/components/Sidebar/SidebarItem.tsx

This PR remove `className` props from `Sidebar` and `Navbar.Item` components.
Fixes #334 
n/a

Remove undesired className prop

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Flowbite/index.tsx
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/helpers/mergeDeep.spec.ts
src/lib/helpers/mergeDeep.ts
src/lib/theme/default.ts

None.
- [feat(theme): add sidebar.item.collapsed.noIcon to theme](https://github.com/themesberg/flowbite-react/commit/5908e0b6bba3f2475b6110431bf530b245b76d09)
- [fix(component): use 1st letter of text in collapsed Sidebar.Item wi…](https://github.com/themesberg/flowbite-react/commit/8f0d24c505d7898fcc5242fabf96435ef37f4148)
- [test(helper): update mergeDeep tests to more closely reflect actual…](https://github.com/themesberg/flowbite-react/commit/7b2d11296d8af3b7a7d798452ab0bf7893809f89)

fix(component): use 1st letter of text in collapsed Sidebar.Item with no icon

---

package.json

The `package.json` was saying that the minimal requirement to the librabry was `react` and `react-dom` 17. It isn't true.
n/a
- Hardware:
- Toolchain:
- SDK:

fix(package): minimal react version is 18

---

src/lib/components/Modal/index.tsx
src/lib/components/Table/TableContext.tsx
src/lib/components/Table/index.tsx

`TableContext` is already defined as the type and also redeclared a `React.Context`. Hence renamed the typedef as `TableContextType` and update the Table component.
The 2nd commit resolves #350 ❤

fix #350: hydration issue with SSR/SSG and re-declaration of TableContext

---

src/docs/pages/PaginationPage.tsx
src/lib/components/Pagination/Pagination.spec.tsx
src/lib/components/Pagination/index.tsx

+ Added test for changing pagination text.
+ Added an example on how change default Pagination text.
In this PR, I've added a new feature to change default `Previous` and `Next` text in the Pagination component. This was made possible by creating two new optional props called `previousText` and `nextText`.
None.
I've ran the example pages and created an unit test exclusively for this new feature.

+ Added props to change Previous and Next text on Pagination.

---

README.md

I updated the "Read about the licensing terms" link in the README file. The link was directing users to https://flowbite.com/getting-started/license/, which gives a 404 error. The updated link is https://flowbite.com/docs/getting-started/license/
Fixes # 371
N/A
I tested the new URL to ensure that it takes the user to the correct License page on the Flowbite site.
- Hardware:
- Toolchain:
- SDK:

Updated license link in README.md file

---

package.json
yarn.lock

Fixes https://github.com/themesberg/flowbite-react/issues/372
Welcome page is broken because of `mdx-js/react v2` it doesn't work after `React18` update. 
Here the opened issue which addresses this problem https://github.com/storybookjs/storybook/issues/18094
And this is a possible way to fix it for now https://github.com/storybookjs/storybook/issues/18094#issuecomment-1217135470 
Manualy by running storybook:start

fix(storybook): fix welcome page

---

src/lib/components/Button/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/theme/default.ts

This PR reduces the thickness of the button outline when the outline prop is set to true.
Fixes [#361](https://github.com/themesberg/flowbite-react/issues/361)
No breaking changes
Manually (Visually)

fix(button): reduce the thickness of button outline

---

src/docs/pages/AvatarPage.tsx
src/lib/components/Avatar/Avatar.spec.tsx
src/lib/components/Avatar/index.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/theme/default.ts

Refs: #357
This PR adds a new prop, `placeholderInitials`, to the `Avatar` component. String passed in this prop will be displayed as `Avatar`'s placeholder, if image is not provided.
Fixes #357 
No breaking changes
Just checked visually
[Screencast from 10-10-22 01:57:39 AM IST.webm](https://user-images.githubusercontent.com/51338731/194778097-ea0ceee2-d2be-4763-8267-54231c806110.webm)

feat: allow using initials as `Avatar` placeholder

---

src/docs/pages/ThemePage.tsx
src/lib/components/Flowbite/index.tsx

Exported `useTheme` and `useThemeMode` hooks from `ThemeContext` and updated theme docs.
fix #389

feat(themecontext): exported theme hooks and updated docs

---

src/lib/theme/default.ts

Fixed the flowbite tooltip which appears on the hover of the sidebar. The tooltip goes behind a card which is fixed now.
Before:
After:
Fixes #359 
- Hardware:
- Toolchain:
- SDK:

flowbit-tooltip is behind card issue fixed

---

src/lib/components/Button/index.tsx

Added forwardRef to button component to work with Next.js' Link component.
fix #341
This PR adds `forwardRef` to Flowbite's `Button` component to ensure, that it works nicely with the `Link` component from Next.js.

feat(button): added forwardRef to button component

---

src/lib/components/Dropdown/Dropdown.spec.tsx
src/lib/components/Dropdown/DropdownItem.tsx
src/lib/components/Dropdown/index.tsx
src/lib/components/Floating/index.tsx
src/lib/helpers/uuid.ts

Closes the dropdown floating menu whenever a DropdownItem is clicked.
Inside `Dropdown/index.tsx`, a mapping function is executed that extends the `onClick` props of all instances of DropdownItem. The extended lines trigger a local state change to `closeRequestKey` that is passed to the `Floating/index.tsx` component.
`setOpen(false)` is called inside the Floating component whenever the closeRequestKey is changed to a unique string generated by the UUID helper function. 
This emulates the Dropdown component requesting Floating to close itself. This is the only workaround that I can think of due to how the component is designed. Floating is contained with Dropdown, preventing other ways of passing control of the `open` state to Dropdown and its child.
We can move this entirely in …

fix(dropdown): close dropdown when item is selected

---

docs/content/components/spinner.md

This PR moves the spinners documentation from the [current documentation page](https://flowbite-react.com/spinners) to Hugo. It looks similar to the alert example that can be found [here](https://github.com/themesberg/flowbite-react/blob/main/docs/content/components/alerts.md)
Fixes #291 and has no breaking changes.
N/A
N/A

docs: migrate the Spinners to Hugo

---

src/lib/components/Floating/Floating.tsx

The dropdown component in the hover trigger mode mouse enter was working fine ok, but mouse leave, the dropdown items were not clickable, the dropdown would close too
Fixes #394  
I have visually checked the changes on the storybook on my local machine here is a recording of this working.
https://user-images.githubusercontent.com/75097551/199706925-269f46ba-617a-4647-b053-4f90742b00aa.mov
- Hardware:
- Toolchain:
- SDK:

Fix inline dropdown bug

---

src/lib/components/DarkThemeToggle/DarkThemeToggle.spec.tsx
src/lib/components/Flowbite/ThemeContext.tsx

The DarkThemeToggle component's button is now working when `usePreferences=true`.
Fixes #417 

fix(DarkThemeToggle): should toggle the theme with `usePreferences` is false (#417)

---

src/lib/components/Sidebar/Sidebar.stories.tsx
src/lib/components/Sidebar/SidebarCollapse.tsx

Added defaultIsOpen prop to SidebarCollapse; Added storybook component to demonstrate using defaultIsOpen.
This PR superseed #388 
N/A
- Import the `Sidebar.Collapse` into an existing `Sidebar` component
- Add the `defaultIsOpen` prop
- Verify the sidebar dropdown is expanded by default on page load
- Remove the flag and refresh
- Verify the dropdown is collapsed

Oxytj sidebarcollapse default isopen

---

src/lib/components/Accordion/index.ts
src/lib/components/Avatar/index.ts
src/lib/components/Breadcrumb/index.ts
src/lib/components/ButtonGroup/index.ts
src/lib/components/Dropdown/index.ts
src/lib/components/Floating/index.ts
src/lib/components/Footer/index.ts
src/lib/components/ListGroup/index.ts
src/lib/components/Modal/index.ts
src/lib/components/Navbar/index.ts
src/lib/components/Pagination/index.ts
src/lib/components/Rating/index.ts
src/lib/components/Sidebar/index.ts
src/lib/components/Tab/index.ts
src/lib/components/Table/index.ts
src/lib/components/Timeline/index.ts

fix #433
list of components that the types were not being exported correctly:
Fixes #433

feat(components): export components types

---

src/docs/pages/AvatarPage.tsx
src/lib/components/Avatar/Avatar.spec.tsx
src/lib/components/Avatar/Avatar.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/theme/default.ts

1. Adds color property to Avatar component to change image ring color. Works only if border property is true. 
2. Adds 'color' test case to the Avatar`s Theme test case
#409
Implements avatar component enhancement introduced by @tiagossa1 The component has ability to change image ring color via prop `color` if `bordered` prop is true.
Fixes #409
`'should use custom colors'` case was added to `'Components / Avatar'` -> `'Theme'` in Avatar.spec.tsx 
Storybook story works correct without any updates.

feat(avatar): adds color prop and test case for it

---

src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Sidebar/SidebarItem.tsx
src/lib/theme/default.ts

Allows users to customize the `label` of a `Sidebar.Item` in the `<Flowbite theme={}>`.
N/A

 feat(/components/sidebar): add Sidebar.Item label to theme 

---

src/lib/components/Toast/ToastToggle.tsx

Adds access to `className` to `ToastToggle` component.
Fixes #444 
N/A
N/A

fix(toast): ToastToggle must have className

---

src/lib/components/Flowbite/Flowbite.tsx
src/lib/helpers/mergeDeep.spec.ts
src/lib/helpers/mergeDeep.ts

`helpers/mergeDeep` has got potential cases when we can mutate target or source objects, it doesn't effected to theme for now but it could be a problem someday. Now it should cover all cases. Returned type also fixed.
Test cases added.

fix(helpers/mergedeep): fix potential cases when source or target obects can be mutated

---

src/docs/pages/AvatarPage.tsx
src/docs/pages/DemoPage.tsx
src/lib/components/Avatar/Avatar.spec.tsx
src/lib/components/Avatar/Avatar.stories.tsx
src/lib/components/Avatar/Avatar.tsx

Changes the Avatar `img` prop to either be a string or a render prop that returns a React element. That makes it so any of the props can be overridden, or an entirely different element could be used in its place.
The docs site doesn't support the render prop syntax by default, so I added a small extension that allows the docs pages to provide a `rawCode` property which is passed directly to the syntax highlighter instead of generating the code sample from the `code` JSX.
Fixes #482

feat(Avatar): Support overriding the Avatar img element. Fixes #482

---

src/docs/pages/TabsPage.tsx
src/lib/components/Tab/Tabs.spec.tsx
src/lib/components/Tab/Tabs.tsx

I have a use case where I'd like to switch to Tab 2 after a performed action on Tab 1, i.e. I'd either need `setActiveTab` exposed or props enabling the switch.
Playing around with `TabItemProps.active`, I got to a first iteration where `TabsComponent` has an extra `useEffect` that switches active tab reacting to `TabItemProps.active` changes. However, this approach presented one major bug, consider the following sequence of action and effects:
1. Tab 2 has `TabItemProps.active == true`
2. User switches to Tab 3 (using standard top buttons)
3. Parent component attempts to switch back to Tab 2, but Tab 2 still has `TabItemProps.active == true`, so `useEffect` is not called.
Syncing state and props to resolve that felt too complex and invasive.
Instead, I forwarded a ref that exposes …

Expose setActiveTab to ref

---

src/lib/components/Modal/Modal.spec.tsx
src/lib/components/Modal/Modal.tsx

Fixes initial focus inside a modal
When using a modal, its content is not initially rendered to the DOM. This causes that it's not possible to control it. For example this was not working:
```tsx
export default () => {
const [isOpen, setIsOpen] = useState(false);
const setInputRef = useCallback(
(input: HTMLInputElement | null) => {
if (isOpen && input) {
input.focus();
}
},
[isOpen]
);
return (
<>
<Button onClick={() => setIsOpen((x) => !x)} />
<Modal show={isOpen}>
<TextInput ref={setInputRef} />
</Modal>
</>
);
};
```

fix(modal): fix initial focus inside a modal

---

src/lib/components/Modal/Modal.spec.tsx
src/lib/components/Modal/Modal.tsx

This clears the modal container ref introduced here: #495

fix(modal): clear modal container ref on unmount

---

src/lib/components/Timeline/Timeline.spec.tsx
src/lib/components/Timeline/Timeline.tsx
src/lib/components/Timeline/TimelinePoint.tsx
src/lib/theme/default.ts

remove margin-top while timeline horizontal and change align-items center to base-line 
before:
after
- Unit Test
- N/A

fix: timeline-horizontal

---

src/lib/components/Avatar/Avatar.spec.tsx
src/lib/components/Avatar/Avatar.tsx

This PR fixes an issue with the `Avatar` component where the `color` prop is ignored when using placeholder initials.
Partially Fixes #451
None

fix: render border colors in Avatar with placeholder initials

---

package.json
src/lib/components/Floating/Floating.tsx
src/lib/helpers/floating.ts
yarn.lock

[react-dom-inteactions](https://www.npmjs.com/package/@floating-ui/react-dom-interactions) is deprecated. This change replaces the two @floating-ui deps to one.
All existing tests are passing

chore: remove deprecated @floating-ui/react-dom-interactions

---

src/lib/theme/default.ts

`Button` with `outline={true}` and `fullSized={true}` creates a button as displayed below:
It should appear as the entire width of the inner section (span). 
Fixes #466
- Create a `Button` with `outline={true}` and `fullSized={true}` and check.
- Open the `Button` component in the storybook and make both the properties (`outline` and `fullSized`) `true` and check.
- Hardware:
- Toolchain:
- SDK:

fix button outline with fullSized issue

---

src/lib/components/ToggleSwitch/ToggleSwitch.stories.tsx
src/lib/components/ToggleSwitch/ToggleSwitch.tsx

Only add ToggleSwitch color classes when Toggle is checked (same behavior as in the [Flowbite Docs](https://flowbite.com/docs/forms/toggle/)).
Improved ToggleSwitch Story to make the Toggle clickable.
Fixes #542 
Tested Component in Storybook.

fix toggleswitch color when checked #542

---

src/docs/pages/FormsPage.tsx
src/lib/components/Flowbite/FlowbiteTheme.ts
src/lib/components/Label/Label.spec.tsx
src/lib/components/RangeSlider/RangeSlider.spec.tsx
src/lib/components/RangeSlider/RangeSlider.stories.tsx
src/lib/components/RangeSlider/RangeSlider.tsx
src/lib/components/RangeSlider/index.ts
src/lib/components/index.ts
src/lib/theme/default.ts

Implemented the `RangeSlider` component as described in the core library.
This component has:
- Theme support
- Storybook
- Unit test
- Documentation
Fixes #188 
- Create a `RangeSlider` with `sizing` and `theme` optional props.
- Allowed all the HTML attributes of `<input type="range" />`
- RangeSlider component in storybook
- Documentation in the Forms section (see the below screenshot)
- Hardware:
- Toolchain:
- SDK:

feat(RangeSlider): range slider with custom theme, storybook, unit test and docs

---

src/docs/pages/ThemePage.tsx
src/lib/components/Alert/Alert.spec.tsx
src/lib/components/Alert/Alert.tsx

Adds tests for the`Alert` component. 
Fixes typo in the documentation pages (the default color for Alert is 'info', not 'primary'). In fact 'primary' does not exists in the FlowbiteColors -> `Pick<FlowbiteColors, 'failure' | 'gray' | 'info' | 'success' | 'warning'>`
Related to #500 
N/A

feat(theme): add tests for alert component

---

src/lib/components/Checkbox/Checkbox.spec.tsx
src/lib/components/Checkbox/Checkbox.tsx
src/lib/components/Radio/Radio.spec.tsx
src/lib/components/Radio/Radio.tsx
src/lib/components/ToggleSwitch/ToggleSwitch.spec.tsx
src/lib/components/ToggleSwitch/ToggleSwitch.tsx
src/lib/theme/default.ts

Add the `theme={}` property to:
Related to #465 , #443 and #500
All main components now have their own styles under `root` object.
Unit tests
**Test Configuration:**
N/A

feat(theme): add theme support for Checkbox, Radio and ToggleSwitch

---

README.md

This information needs to be extremely accessible now.
None

docs(readme): refer to theme docs page in `README`

---

src/lib/components/Button/Button.tsx
src/lib/components/Carousel/Carousel.tsx

fix #646
This PR just adds the `DeepPartial` type to optional custom themes for two components (Button & Carousel) that were missing that. For both, deep merging with the base theme was already setup.
Fixes #646 
None.
Just the regular tests with `yarn test`, and linting tests with prettier and eslint.

fix(button/carousel): added DeepPartial Typing

---

src/lib/components/Flowbite/ThemeContext.tsx

The variable `userPreferenceIsDark` was initialized with a value from the window object. This was causing an error with Next because of SSR. I added the check of the window, if it's on the server side the value is set to `false`
On my Next.js project that was causing the error.

fix(themecontext): fixing `ReferenceError: window is not defined` error with Next.js

---

src/lib/theme/default.ts

By using this code:
```jsx
<Button fullSized={true} outline={true}>
Acessar
<HiArrowRight className="w-5 h-5 ml-2" />
</Button>
```
It caused this error:
No
- Manual test
- Unit test still working

fix(button): fixes outline button

---

src/lib/components/Dropdown/Dropdown.tsx

This PR fixes the **Dropdown** component documentation so that it runs as-is. A missing _displayName_ property caused the documentation to render an invalid name for the component.
Related to #616

docs(component): fix missing DropdownComponent displayName property

---

src/docs/pages/AvatarPage.tsx
src/lib/components/Avatar/Avatar.spec.tsx
src/lib/components/Avatar/Avatar.tsx
src/lib/theme/default.ts

This PR removes the hard-coding of width and height styling applied to any `Avatar` component using the `placeholderInitials` property, and adds in the size class when rendering so that it is rendered in the expected size.
Fixes: https://github.com/themesberg/flowbite-react/issues/659
None.
Tested locally, tested in an external CRA via `link` and also tested via a previously failing unit test (included in PR).
N/A

fix(/src/components/avatar): enable explicit sizing of placeholder initials (#659)

---

src/lib/theme/default.ts

As of the changes of #601 (fixing #600), modals can no longer be positioned vertically. This is because the height of the modal is always 100% and thus `items-start`, `items-center` or `items-end` do not affect the flex items. This PR reverts the simple change made that broke this.
The bug can be observed in the docs [here](https://flowbite-react.com/modal) where positioning the item anywhere but the top does nothing.
In my opinion, the fix for overflowing modals seen in #601 and also suggested on #537 is not accurate. Setting a max height for your modal when using the component is more than sufficient to fix this issue on any given project, but eventually having a fix on this package could be ideal (some of this discussion overlaps with #520).
Manually adding `md:h-auto` to my own …

fix(modal theme): fix modal vertical positioning

---

src/lib/components/Sidebar/Sidebar.tsx

`className` was present on Sidebar, 'cause it extends `div`, but it wasn't working properly. This PR, adds the `className` to the end of CSS classes, as we have in other components.
No

fix(sidebar): adds missing className

---

src/lib/components/Progress/Progress.tsx
src/lib/theme/default.ts

Progress bar shows labels even when it is disabled at progress value is 0
The conditional rendering using the '&&' would return 0 on condition being false which would get displayed when progress value is 0. This was fixed using ternary operator instead. And also the label would get hidden at low progress values which is now 
Fixes #696
Tested by trying to set the progress value to zero in the storybook.

fix(component/progressbar):  fix progressbar showing label when progress == 0

---

src/lib/components/Sidebar/Sidebar.tsx

In some cases, the sidebar is the main navigation of an app and setting using
```
<Sidebar as="nav">
...
</Sidebar>
```
would be more appropriate.

feat(sidebar): Allow to customize the Sidebar component with 'as'

---

src/lib/theme/default.ts

Fixing a typo.  It was #715, but now using a different branch.

fix(theme): typo in bottom-center

---

src/lib/components/Dropdown/Dropdown.spec.tsx
src/lib/components/Dropdown/Dropdown.tsx

Adding the type button to be able to use the dropdown inside the form. 
Same as used in example from https://flowbite.com/docs/forms/select/#select-with-dropdown
Fixes #756
Check that the form submission is being sent at the correct time and is working.
I checked if the button type was correct in the inspect element, and it's ok

fix(dropdown): add type button in dropdown

---

src/lib/components/ToggleSwitch/ToggleSwitch.tsx

Based on #736 , ToggleSwitch color prop was not defined as keyof FlowbiteColors which was causing a build error.
Fixes #736 
Using a project test, I was able to navigete to the type definition and perform the modification on the fly. So the component itself was able to show whether it was working properly or not. After that I built the project and it worked as expected
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

fix: making ToggleSwitch color prop as keyof FlowbiteColors

---

src/lib/theme/default.ts

A unnecessary Tailwind class was being used causing the PaginationButton to not highlight itself correctly when active.
Fixes #719
For testing this fix, I ran Storybook locally to make sure the fix would be enough. Now the current page selected button is being highlighted correctly both on light and dark mode.
- …

fix: pagination button not being highlighted correctly

---

src/components/Modal/Modal.tsx

Flowbite modal removes the scroll bar forever if I toggle it from Flowbite footer component.
Fixes # [761](https://github.com/themesberg/flowbite-react/issues/761)
- [ x] Bug fix (non-breaking change which fixes an issue)
I tested this change by running the documentation site locally and toggling the Modal from the bottom works fine from my end the scrollbar doesn't remain hidden when I close the Modal

fix(Modal): modal scrollbar overflow style issue fixed

---

src/theme.ts

The modal's position property is handled by the parent of the actual content box using flex, align-items, and justify-content but was blocked by the content box's property of "margin: auto" (m-auto). This fix deletes that property so the parent can correctly handle the position of the modal correctly.
Fixes #760 
I tested this change by running the documentation site locally and checking whether the property works correctly on the Modal component page.

fix(modal): fixed a bug that disallowed users to set the position of a modal

---

app/layout.tsx
tailwind.config.js

Properly import the `Inter` font from Google Fonts via Next configuration.
Fixes # [(issue)](https://github.com/themesberg/flowbite-react/issues/789)
You can test via the browser and network tab.

docs(font): load Inter font from Next

---

app/docs/components/accordion/accordion.mdx
app/docs/components/alert/alert.mdx
app/docs/components/avatar/avatar.mdx
app/docs/components/badge/badge.mdx
app/docs/components/breadcrumb/breadcrumb.mdx
app/docs/components/button-group/button-group.mdx
app/docs/components/button/button.mdx
app/docs/components/card/card.mdx
app/docs/components/carousel/carousel.mdx
app/docs/components/dropdown/dropdown.mdx
app/docs/components/footer/footer.mdx
app/docs/components/forms/forms.mdx
app/docs/components/list-group/list-group.mdx
app/docs/components/modal/modal.mdx
app/docs/components/navbar/navbar.mdx
app/docs/components/pagination/pagination.mdx
app/docs/components/progress/progress.mdx
app/docs/components/rating/rating.mdx
app/docs/components/sidebar/sidebar.mdx
app/docs/components/spinner/spinner.mdx
app/docs/components/table/table.mdx
app/docs/components/tabs/tabs.mdx
app/docs/components/timeline/timeline.mdx
app/docs/components/toast/toast.mdx
app/docs/components/tooltip/tooltip.mdx

For now, we're just including the snippet of Tailwind CSS classes that are applied to each key in the component's theme. That makes it easy to figure out where you need to make tweaks to the theme. I'm not sure how we can make it more useful yet - we will want to get feedback on this.
Starts working toward #808
None

docs: add Theme section to each component's docs

---

app/docs/layout.tsx
app/page.tsx
src/components/DarkThemeToggle/DarkThemeToggle.tsx
src/components/Navbar/Navbar.tsx
src/components/Sidebar/SidebarItem.tsx
src/components/Sidebar/theme.ts
vitest.config.ts

This PR adds a few changes, most of them related to my usage experience.
- Adds `iconLight` and `iconDark` as optional props to `DarkThemeToggle` component;
- Fixes the `theme` component props for `Navbar` component;
- Adds access to the `listItem` element to the `SidebarItem` theme;
- Excludes `lib/**/*` from `vitest`, it seems that only excluding `lib` in this case wasn't actually working well...
`Navbar` component now access the correct theme interface, and it could break any customization for this component. The new format is visible in the documentation. …

feat: life quality improvements

---

app/docs/components/button/button.mdx
src/components/Button/Button.spec.tsx
src/components/Button/Button.tsx

Fixes #655
As @tulup-conner commented [here](https://github.com/themesberg/flowbite-react/pull/681#issuecomment-1579567168), I decided to create a new PR with the simplest solution based on the SidebarItem component.
No breaking changes
- Hardware:
- Toolchain:
- SDK:

feat(button.tsx): Added as prop to button component

---

src/components/Button/Button.stories.tsx
src/components/Button/theme.ts

Removed the specific `disabled:hover:*` and `dark:disabled:hover:*` classes from button theme and added `enabled` to all `hover:*` classes so there is no hover effect when button is disabled and still keep the cursor not-allowed.
Fix #827
LIGHT MODE
DARK MODE
Added `disabled` prop to all possible button colors and checked the hover state in light and dark modes
- Hardware:
- Toolchain:
- SDK:

fix(button.tsx): Disable Button hover state when button is disabled

---

src/components/TextInput/TextInput.tsx

Fixes #828
Visible in the Documentation app
- Hardware:
- Toolchain:
- SDK:

fix(textinput.tsx): TextInput padding when having right/left icons

---

app/docs/layout.tsx
app/page.tsx
src/components/Navbar/Navbar.tsx

You should only put the contents of `useTheme().theme.navbar.root` here, not
`useTheme().theme.navbar` as a whole. To migrate if you use `<Navbar theme={}`, remove `root: { ..
}` from your custom theme. If you customized child components here, you'll need to move those
changes to each child's `theme={}` attribute.
TODO

 fix(src/components/navbar): fix wrong type on <Navbar theme>

---

app/docs/components/dropdown/dropdown.mdx
src/components/Dropdown/Dropdown.spec.tsx
src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/Dropdown.tsx

Include the `renderTrigger` property to `Dropdown` component. It allows users to completely overwrite the `Dropdown` trigger element.
Fixes #624
None.
N/A

feat(dropdown): adding custom trigger

---

app/docs/components/carousel/carousel.mdx
src/components/Carousel/Carousel.tsx

Include the property `onChangeSlide` to `Carousel` component. It will allow users to hook custom behaviors when the slide changes.
Fixes #596
None.
N/A

feat(carousel): adds onSlideChange property

---

src/components/Modal/theme.ts

I noticed some weird behavior for the modal backdrop when trying to reproduce the #829, the modal's backdrop wasn't covering 100% of the screen height is some cases. This PR should fix this problem...
None
N/A

fix(modal): backdrop height

---

app/docs/components/dropdown/dropdown.mdx
package.json
src/components/Button/Button.tsx
src/components/Button/ButtonBase.tsx
src/components/Button/theme.ts
src/components/Dropdown/Dropdown.spec.tsx
src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownItem.tsx
src/components/Dropdown/theme.ts
src/components/Floating/Floating.tsx
src/helpers/floating.ts
src/helpers/use-floating.ts
yarn.lock

This PR enables the `Dropdown.tsx` component to be navigated by keyboard, improves the Dropdown.Item component to be rendered using `as` prop, and fixes the dismiss on click and `disabled` trigger issues.
Fixes #648. Fixes #793 . Fixes #539 
The package resolution added in `package.json` was necessary due to some errors being thrown in the tests when using `FloatingFocusManager` component. See: https://github.com/focus-trap/focus-trap-react/issues/986
TBD

feat(dropdown.tsx): Dropdown Accessibility

---

app/docs/components/card/card.mdx
src/components/Card/Card.spec.tsx
src/components/Card/Card.stories.tsx
src/components/Card/Card.tsx
src/helpers/omit.spec.ts
src/helpers/omit.ts
yarn.lock

Since in some cases, for example next.js apps, one needs to use a specific and optimized `Image` component, the `Card` component now accepts a `renderImage` property to render your own component. If `renderImage` is set, `imgSrc` and `imgAlt` are ignored. TypeScript will error if the user attempts to set them at the same time.
fix #706 
To do:

feat(card): support custom renderImage functions for Card

---

app/docs/components/toast/index.tsx
app/docs/components/toast/toast.mdx
src/components/Toast/Toast.spec.tsx
src/components/Toast/Toast.tsx
src/components/Toast/ToastToggle.tsx
src/components/Toast/theme.ts

This PR adds the ability to convert the `Toast` component into a stateless mode by providing `onDismiss` to `Toast.Toggle`.
It also changes the default hiding behaviour. Now the Toast is removed from the DOM when `isRemoved = true`. Finally, it adds by default `role="alert"` to the toast root
Fix #848 
The theme property `root.removed` has been removed as it will not be needed anymore.

feat(toast.tsx): Stateless Toast

---

app/docs/components/button/button.mdx
src/components/Button/Button.spec.tsx
src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx
src/components/Button/theme.ts
tailwind.config.ts

*Summarize the changes made and the motivation behind them.*
This PR makes the <Spinner /> component inside the <Button /> component to be relative to the Button size when `isProcessing=true`. It also adds an width animation when the flag is toggled.
Fix #850 

fix(button.tsx): Relative Spinner size

---

src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

`twMerge` is removing the padding classes for the `Select.tsx` component when an icon is passed.
I also checked if the issue was happening in other components too and I noticed tha the `Badge.tsx` component had the same problem. Even though it was not breaking visually when a Badge had an icon, if the user passes a `p-` class to the custom theme object it was not being applied due to the preference ordering in `twMerge`
Fix #869

fix(select.tsx/badge.tsx): With icon classes preference

---

app/docs/components/button/button.mdx
app/docs/components/dropdown/dropdown.mdx
src/components/Button/Button.spec.tsx
src/components/Button/Button.tsx
src/components/Button/ButtonBase.tsx
src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownItem.tsx
src/helpers/generic-forward-ref.ts

This fixes the issue with Next `Link` component which also uses the `href` prop (which the internal logic was always rendering an anchor tag).
It also improves the TS props of Button and DropdownItem components to actually inherit the props of the tag/component  passed in the `as` prop, instead of using `extends Record<string, unknown>`. 
Fix #865

fix(button.tsx): Button `as` prop internal logic + TS props

---

src/components/Button/Button.tsx

Due to a recent change with `<Button />`, the `displayName` was removed from the component. This had a downstream effect of causing the docs to report that the name for this component was "No Display Name".
This change simply adds back the display name.

fix(button.tsx): Adding back displayName

---

app/components/carbon-ads.tsx
app/components/code-preview.tsx
app/components/component-card.tsx
app/components/docs-content-layout.tsx
app/docs/layout.tsx
app/page.tsx
src/components/Modal/Modal.spec.tsx

This PR is not yet finished - throws an error for using `useRouter` instead of `next/navigation`.

docs: integrate Carbon Ads

---

app/components/navbar.tsx
app/page.tsx

I've added the Discord Icon and link to the navigation and slightly improved the footer styles for the homepage by increasing the contrast between section by adding `bg-gray-50`. Also moved the link from GitHub pages to https://storybook.flowbite-react.com/ for the StoryBook link.

Discord Community & Footer improvements

---

app/docs/components/carousel/carousel.mdx
src/components/Carousel/Carousel.tsx

A new property on the <Carousel> component, `pauseOnHover`, will improve accessibility, allow for a faster flow of information, and help users find desired information quicker. From the Web Accessibility Initiative in "What makes a carousel accessible?", they note: "Users must be able to pause carousel movement because it can be too fast or distracting, making text hard to read." (www.w3.org/WAI/tutorials/carousels/) Currently, there is no built in feature to accomplish this. Developers will either have to disable the `slide` property, or make the `slideInterval` property very long to allow users to read necessary information. With the `pauseOnHover` property, users will have a quick way, both on mobile and desktop, to pause on …

feat(component): new pauseOnHover prop to <Carousel>, provide quick information with chance to pause

---

README.md
app/components/banner.tsx
app/docs/getting-started/introduction/introduction.mdx
app/docs/getting-started/quickstart/quickstart.mdx
app/docs/layout.tsx
app/page.tsx

I have added an announcement banner to the docs and home pages which we can now use to increase awareness for the Server Components discussion and we can also use it for future releases, feedbacks, and more.
Here's how it looks:
@tulup-conner if you want to create the poll discussion let me know so we can change the URL - if you have anything to add in terms of content feel free to update the PR before merging. We should get this online ASAP.

Announcement banner

---

app/docs/layout.tsx

Fixes a missing piece of the border after adding the banner component:
How it looks after the fix:

Fix sidebar border styles

---

app/docs/components/sidebar/sidebar.mdx
src/components/Sidebar/Sidebar.spec.tsx
src/components/Sidebar/SidebarCollapse.tsx
src/components/Sidebar/theme.ts

Adds the `chevronIcon` and `renderChevronIcon` properties to `Sidebar.Collapse` component, allowing users to customize the chevron icon for collapsed sidebar items.
**BREAKING CHANGE:**
`FlowbiteSidebarCollapseTheme` signature changes:
```diff
label: {
base: string;
-    icon: string;
+    icon: {
+      base: string;
+      open: FlowbiteBoolean;
+    };
}
```
Closes #888

feat(sidebar): add custom chevron icon to collapse

---

app/components/banner.tsx

I have updated the banner announcement content and link to the new poll discussion.
We should keep it open at least for one week.

docs(banner): update banner info for the new poll

---

app/docs/components/timeline/timeline.mdx

docs: add missing external imports for Timeline Component

---

src/components/Button/theme.ts

tailwind-merge was trashing `bg-white` because of this floating class. I'm assuming this is supposed to be a `dark:` class

Add dark: to button light theme

---

app/docs/components/banner/banner.mdx

I've checked the banner component and I'd like to do the following changes:
The button is too large, we should make it smaller:
The elements should span the whole width of the screen:
--
For reference we can check out the [banners from the main Flowbite Library](https://flowbite.com/docs/components/banner/).

docs(banner): update `blue` colors to `cyan` & fix button paddings

---

src/components/Textarea/theme.ts

Fixes an older design problem from the main library where the `Textarea` component had `text-base` font size instead of `text-sm` - this change applies `text-sm` by default to keep consistency.

fix(textarea): default font size should be `text-sm`

---

src/components/Alert/Alert.stories.tsx
src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/AvatarGroup.stories.tsx
src/components/Badge/Badge.stories.tsx
src/components/Button/Button.stories.tsx
src/components/Button/ButtonGroup.stories.tsx
src/components/Carousel/Carousel.stories.tsx
src/components/Checkbox/Checkbox.stories.tsx
src/components/DarkThemeToggle/DarkThemeToggle.stories.tsx
src/components/Dropdown/Dropdown.stories.tsx
src/components/FileInput/FileInput.stories.tsx
src/components/Footer/Footer.stories.tsx
src/components/Label/Label.stories.tsx
src/components/ListGroup/ListGroup.stories.tsx
src/components/Modal/Modal.stories.tsx
src/components/Navbar/Navbar.stories.tsx
src/components/Pagination/Pagination.stories.tsx
src/components/Progress/Progress.stories.tsx
src/components/Radio/Radio.stories.tsx
src/components/RangeSlider/RangeSlider.stories.tsx
src/components/Rating/Rating.stories.tsx
src/components/Select/Select.stories.tsx
src/components/Spinner/Spinner.stories.tsx
src/components/Table/Table.stories.tsx
src/components/TextInput/TextInput.stories.tsx
src/components/Textarea/Textarea.stories.tsx
src/components/Timeline/Timeline.stories.tsx
src/components/Toast/Toast.stories.tsx
src/components/ToggleSwitch/ToggleSwitch.stories.tsx
src/components/Tooltip/Tooltip.stories.tsx

@storybook/react deprected Use of Story. 
`@deprecated` Use `StoryFn` instead.

docs: story `@deprecated` Use `StoryFn` instead

---

src/helpers/generic-forward-ref.ts

Fix error after updating to v0.6.0 Button cannot be used as a JSX component. Its return type 'ReactNode' is not a valid JSX element.
fix #962

fix(button): fix error Button cannot be used as a JSX component

---

src/components/Datepicker/Datepicker.tsx

This change fixes the issue with the custom themes not being applied to the Datepicker views and adds a callback function in order to be able to get the selected date
Fixed #968 #964 
Added a new prop `onSelectedDateChanged` to `Datepicker` but it is optional and therefore should not be a breaking change.

fix(datepicker.tsx): fix theme and add onSelectedDate callback

---

src/components/Label/theme.ts

The dark mode colors of the label input should be white instead of `gray-300`.
We should also make the default checkbox, radio, and toggle colors as such:
`text-gray-500` and `dark:text-gray-300`
For the toggle switch I see there's a separate theme file, but for the Checkbox and Radio elements it inherits the one from the form labels which should be separate as well, in my opinion.
This PR addresses the form input element labels above the inputs and makes them white on dark mode.

fix(labels): default dark color of the input labels should be white

---

src/components/Tab/Tabs.tsx
src/components/Tab/theme.ts

Tabs inside Tab component are wrapped in an unstyled div, and in no way this was possible to add any style to it. I added a now theme key "tabsitemcontainer" to let the div take in style. As it was possible to style the divs inside (the single tabs), it was kinda stupid not being able to add style to a div that contains them, as it brought issues with dimensions.
#924
Yes. I added a key to the theme of the tabs, the theme i added is completely empty and is done only for users to implement some custom …

fix(tabs): added tabs container div style and theme

---

src/components/DarkThemeToggle/DarkThemeToggle.tsx

A small cleanup by removing redundant imports and reusing existing `useTheme` hook.

refactor: remove redundant `useContext` -> replace with `useTheme`

---

mdx-components.tsx

In the docs section, the heading elements have a `::before` element with a height of `5rem` used solely for scrolling to that area with a top-offset of `5rem`.
`h2/h3` component
https://github.com/themesberg/flowbite-react/assets/41998826/0335dcf2-722d-4c97-ae8e-6de551aed973
`::before` element
Remove the `::before` element with vanilla CSS rule `scroll-margin-top` (https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top)
https://github.com/themesberg/flowbite-react/assets/41998826/d808361b-e74b-45fb-beff-41c5f81b0fd3

fix: scroll to section blocking above content

---

src/components/Datepicker/Views/Days.tsx
src/components/Datepicker/helpers.ts

The weekdays index is based on the "currentDate" variable and it was representing the wrong value that is fixed now
fixes: #960

fix(datepiker): incorrect names of days of the week in the datepicker

---

app/components/code-preview.tsx

If the setting `useBooleanShorthandSyntax` is not set to `false` in the https://github.com/algolia/react-element-to-jsx-string/tree/master options object, it will remove for good any prop looking like this `prop={false}`, even tho the default is set to `true` within the component.
This is a problem because it can misguide people when they look at the code snippet, if they copy it and paste it -> they should see the same results, which today is not the case, for example for https://www.flowbite-react.com/docs/components/datepicker#autohide.
- show explicit false props (eg: `visible={false}`)
- removing `sortProps` since it defaults to `true`
This issue currently affects the following components: 
1. avatar
2. carousel
3. datepicker
4. dropdown
5. rating
6. tooltip

fix: `CodePreview` - show explicit false props

---

app/docs/components/forms/forms.mdx
src/components/ToggleSwitch/ToggleSwitch.tsx

As described in issue #986 the component `ToggleSwitch` wasn't acting as expected when `checked={true} disabled={true}`. This PR fixes the issue. This also replaces the deprecated `onKeyPress` API with `onKeyDown`.
Fixes #986 
⚠️ This PR replaces the `onKeyPress` with `onKeyDown`. It should not break anything, since the API is only internally used.

fix(toggleswitch): disable + checked state and deprecated html event replacement

---

app/page.tsx
src/components/DarkThemeToggle/DarkThemeToggle.tsx
src/components/Flowbite/ThemeContext.tsx

Home page dark mode section buttons do not toggle theme dark/light mode.
- enhance `toggleMode` function to accept custom `mode` value as well in `ThemeContext`
- implement throw error guard in case of using `useTheme` without a context provider
https://github.com/themesberg/flowbite-react/assets/41998826/f508f118-fd61-4f53-9e2b-07175482f637

fix: homepage - missing dark mode section functionality

---

app/docs/components/avatar/avatar.mdx

Docs: fix `Avatar` section `Override image element` code preview.

fix: docs - avatar - render properly code example

---

src/components/ToggleSwitch/ToggleSwitch.stories.tsx
src/components/ToggleSwitch/ToggleSwitch.tsx
src/components/ToggleSwitch/theme.ts

Sizing (sm|md|lg) for ToggleSwitch component
I added some storybook example for now. 
The examples will be on its own /docs/forms/toggleswitch page being worked on in #998.
#998 
added sizing prop. Not a breaking change. default is still md (which has class w-11 h-6 ...)

feat(component): toggleSwitch add sizing prop (sm|md|lg)

---

app/docs/components/button/button.mdx
src/components/Button/theme.ts

Button color=blue was coming up as cyan
#1010 

fix: Button color blue theme

---

src/theme.ts

I made an error in importing the FLoating Label Theme, when I developed the component, now I have fixed the import, and it should be working fine after this fix
https://github.com/themesberg/flowbite-react/issues/1022

fix: Floating Label theme import

---

src/components/Datepicker/helpers.ts

Fixed day suggestions in the top datepicker bar and added support for starting from any day of the week.
https://github.com/themesberg/flowbite-react/issues/1038
If you have ideas on how to simplify or improve it, please comment.
Before:
After:

fix: fix getWeekDays function

---

src/components/Button/theme.ts

fix(button/theme.ts): add the missing dark modifier for Button bg color

---

app/docs/layout.tsx

Remove /docs/components/blockquote link. It exists in /docs/typography/blockquote.
Fixes #1049 

docs: fix broken blockquote link in components. Moved to Typography

---

app/docs/layout.tsx
app/page.tsx

Currently the overflow container is isolated within a nested div, leading to inconsistent preservation of scroll on-page-reload.
https://github.com/themesberg/flowbite-react/assets/41998826/afe7e2cf-2696-4ce6-bdce-a22a22b1ffc0
https://github.com/themesberg/flowbite-react/assets/41998826/50b6d5f0-0a71-400c-b9f7-8306a8b9b2c1

fix: layout overflow

---

app/docs/components/navbar/navbar.mdx

Docs `Navbar` shows incorrect code preview.

fix: docs navbar - incorrect code preview

---

app/docs/components/forms/forms.mdx

Docs forms `Toggle Switch` shows incorrect code preview.

fix: docs forms toggle switch - incorrect code preview

---

app/docs/components/dropdown/dropdown.mdx

Docs dropdown shows incorrect code preview.

fix: docs dropdown - incorrect code preview

---

app/page.tsx

Removed redundant conditional check, `contributors` state is by default initialised with `[]`, and the API `fetch` sets the result only if its successful, therefore it will never have a nullable state where it does not exist.

homepage: remove redundant conditional check

---

CONTRIBUTING.md
app/docs/getting-started/contributing/contributing.mdx

Broken "bug tracker" url.
https://github.com/themesberg/flowbite-react/assets/41998826/4d532ddd-8b95-4bce-8460-a2d9cab3a61b
https://github.com/themesberg/flowbite-react/assets/41998826/7d206b4f-e245-4c17-81e5-9692de17d7cb

fix: docs/getting started/contributing - invalid "bug tracker" url

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownContext.tsx
src/components/Dropdown/DropdownDivider.tsx
src/components/Dropdown/DropdownHeader.tsx
src/components/Dropdown/DropdownItem.tsx

`Dropdown` is missing granular control over the theme object.
#1060
- `DropdownHeader` and `DropdownDivider` now accept `theme` object as well

fix: dropdown theme - granular control

---

app/docs/components/tabs/tabs.mdx
src/components/Accordion/index.ts
src/components/Banner/BannerCollapseButton.tsx
src/components/Datepicker/index.ts
src/components/Dropdown/index.ts
src/components/Navbar/index.ts
src/components/Rating/index.ts
src/components/Sidebar/Sidebar.tsx
src/components/Sidebar/SidebarItemGroup.tsx
src/components/Sidebar/index.ts
src/components/Tab/Tabs.spec.tsx
src/components/Tab/Tabs.stories.tsx
src/components/Tab/Tabs.tsx
src/components/Tab/index.ts
src/components/Table/index.ts
src/components/Timeline/index.ts
src/components/Toast/index.ts

Since RSC does not support compound components (eg: `Table.Row`) and instead they need to be imported as components (eg: `TableRow`), more granular exposure of all Flowbite sub-components has to be done.
This brings support for the following components: 
1. Accordion
2. Dropdown
3. Navbar
4. Rating
5. Sidebar
6. Table
7. Timeline
8. Toast
RSC
```jsx
// works
import { Table, TableHead } from 'flowbite-react';
function Component() {
return (
<Table>
<TableHead>{/* ... */}</TableHead>
</Table>
);
}
```
RSC
```jsx
// does not work, will throw error of "Head" being `undefined`
import { Table } from 'flowbite-react';
function Component() {
return (
<Table>
<Table.Head>{/* ... */}</Table.Head>
</Table>
);
}
```
- `Tabs.Group` is now `Tabs`

RSC - patches

---

README.md

Updated broken doc links to working doc links and also fixed a typo.
Fixes #1088 

Updated broken doc links in readme.md and fixed some typos

---

components/homepage/contributors-section.tsx
components/homepage/dark-mode-section/dark-mode-section.tsx
components/homepage/figma-section.tsx
components/homepage/hero-section/hero-section.tsx
components/homepage/react-section.tsx
components/homepage/social-proof-section.tsx
components/homepage/tailwind-section.tsx
next.config.mjs

https://github.com/themesberg/flowbite-react/assets/41998826/86cf10db-377c-45b3-bc9f-70157c41a7f0
https://github.com/themesberg/flowbite-react/assets/41998826/80ed52aa-46f6-420c-9d7e-8cb754cffb44
https://github.com/themesberg/flowbite-react/assets/41998826/0cb7dceb-9eca-41f7-91fc-e00ef6924604
https://github.com/themesberg/flowbite-react/assets/41998826/ee721e40-2092-4dee-b9cd-1f705c0abf58

homepage: image optimisations, avoid content bounce on reload

---

components/code-highlight.tsx
src/components/DarkThemeToggle/DarkThemeToggle.spec.tsx
src/components/DarkThemeToggle/DarkThemeToggle.tsx

fix hydration error

---

content/docs/components/rating.mdx
src/components/Flowbite/FlowbiteTheme.ts
src/components/Rating/Rating.tsx
src/components/Rating/RatingAdvanced.tsx
src/components/Rating/theme.ts
src/theme.ts

- removed `advanced` from `FlowbiteRatingTheme` interface
Before
After

refactor(components): separate `AdvancedRating` from `Rating` theming

---

src/index.ts

Augment the API and expose `getTheme()`, `getThemeMode()` functions. (discord members/users know better).

API: expose `getTheme()`, `getThemeMode()` functions

---

app/docs/[[...slug]]/page.tsx

Before
After
Same image, but with the correct title and description. I cannot show a preview since the OG only works for published reachable domains, not local environment.

Docs: add open graph meta tags

---

components/banner.tsx
content/docs/getting-started/server-components.mdx
data/docs-sidebar.ts

With the release of v0.7.0 bringing full React Server Components (RSCs) support, we need to update the docs as well.
Banner
Docs `server-components` page

docs: Server components page + banner update

---

content/docs/customize/dark-mode.mdx

With the RSCs support in Next.js app router and the new changes to the core library theme, we need to update the docs as well.

docs dark mode: section for Next.js

---

app/docs/layout.tsx

Make the new badge smaller.
Before
After

docs sidebar: new badge smaller

---

content/docs/forms/file-input.mdx
data/components.tsx
data/docs-sidebar.ts
examples/fileInput/fileInput.dropzone.tsx
examples/fileInput/fileInput.helper.tsx
examples/fileInput/fileInput.multiple.tsx
examples/fileInput/fileInput.root.tsx
examples/fileInput/fileInput.sizes.tsx
examples/fileInput/index.ts
examples/index.ts
public/images/components/file-input-dark.svg
public/images/components/file-input.svg

To create separate pages for /forms/* documentations to match flowbite of existing react components. 

docs(fileinput): standalone page for FileInput component

---

src/components/DarkThemeToggle/DarkThemeToggle.tsx

components(DarkThemeToggle): fix custom icon types

---

src/components/Footer/theme.ts

The link elements were not responsive because there was no default margin set. me-4 was added to
non-react footer but not in react footer.
#1085 
NA

fix(footer>theme.ts): adding margin to right in footer links

---

data/docs-sidebar.ts

Docs sidebar was missing the `List` item;
Before
After

docs sidebar (typography): add missing `List` link

---

src/components/DarkThemeToggle/DarkThemeToggle.tsx
src/hooks/use-is-mounted.ts

Due to `Next.js` hydration process trying to render on server first, then hydrate on client, `data-active` attribute depends on `computedMode` from `useThemeMode` which has the source of storage localstorage. The problem is that there is no valid `computedMode` on server.
Issue:
#1156

components(DarkThemeToggle): fix console warning

---

content/docs/components/datepicker.mdx
examples/datepicker/datepicker.weekStart.tsx
src/components/Datepicker/Views/Days.tsx
src/components/Datepicker/helpers.ts

Updating the WeekStart enum to be aligned with the values Javascript Date object uses allows to simplify the code and maintain compaitbility. Fixed the off-by-one error in the weekdays order.
BREAKING CHANGE: As the WeekStart enum changed order to be aligned with Javascript Date object, now you have to change your weekStart attribute to be -1, so for Monday you should put 1, instead of 2. But it wasn't working before as the values were incorrectly rendered in the first place.
fix #1044
#1044
As the …

fix(datepicker): fix the inconsistent weekday labels

---

content/docs/typography/list.mdx
examples/list/index.ts
examples/list/list.horizontal.tsx
src/components/List/List.tsx
src/components/List/theme.ts

Added new horizontal state to the list component
+ documentaion
New `horizontal` prop added to obtain the state.

feat(list component): develop new horizontal state of list component

---

src/components/DarkThemeToggle/DarkThemeToggle.tsx

`DarkThemeToggle` component crashes due to absolute import which is not resolved by the bundler.
#1182

fix: absolute to relative import

---

src/components/ToggleSwitch/ToggleSwitch.tsx

fix #1078
A forwardRef for the ToggleSwitch component has been added. These changes fixed an error with the forwardRef message appearing when using react-hook-form
This PR will be fix this issue https://github.com/themesberg/flowbite-react/issues/1078

fix(toggleswitch component): added forwardRef to ToggleSwitch component

---

src/components/TextInput/TextInput.tsx

All of the other form components provide an implicit `type=".."` field so this one should, too. It is implied by the name that this will be an `<input type="text">` by default, and you have the *option* to provide a specific other `type`.
Make `<TextInput>`s slightly more convenient when the `type="text"`, since "Text input" implies that.
No breaking changes! `type="text"` typed explicitly will still work, but won't be necessary anymore. Explicit `type="search"`, etc. will work the same.

feat(component): default to `type="text"` on `<TextInput>`

---

src/components/Badge/theme.ts

The original issue was that the blue color on the badge was perceived as cyan, prompting a change to a more suitable color.
Modified the color of the badge from cyan to a blue color.

fix(badge): blue color on badge is cyan

---

src/components/Button/theme.ts

fixes the button inconsistent focus ring compared to the core library. It also adds a transition of colors and ring
This PR fixes the button focus ring, which is currently inconsistent with the core library. The Button Group ring was wrongly overriding the ring-4 classes defined in the button themes.
Also, I took the opportunity to add a slight transition on the button colors/shadows to have the hover and the ring styles animated

fix(button): Button ring on focus

---

components/homepage/components-section.tsx
components/homepage/hero-section/hero-section.tsx
components/homepage/react-section.tsx

Use NextJS `Link` component for internal routes. Avoid full page refresh and improve UX.
https://github.com/themesberg/flowbite-react/assets/41998826/f971741b-80f3-4aca-89c0-a1dc1764e95a
https://github.com/themesberg/flowbite-react/assets/41998826/b52b5211-7335-4a58-b7b3-3ebee3a731b3

fix: homepage - use Link for internal links

---

src/components/Datepicker/Datepicker.stories.tsx

When you click Datepicker on the storybook, throws an `invalid time value` error.
I guess it is because the default value of `weekStart` arg becomes string `Sunday` by the `argTypes.weekStart.mapping`. The `weekStart` arg is expected the number.
This PR fixed the value of `argTypes.weekStart.mapping` to be only the string key.
```diff
- argTypes.weekStart.mapping: { 0: "Sunday", 1: "Monday", 2: "Tuesday", 3: "Wednesday", 4: "Thursday", 5: "Friday", 6: "Saturday", Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6 }
+ argTypes.weekStart.mapping: { Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6 }
```
fix #1167

fix(storybook): fix the `argTypes.weekStart.mapping` on `Datepicker.stories.tsx`

---

examples/timeline/timeline.horizontal.tsx

Timeline Horizontal example in the Docs was missing the horizontal boolean value on <Timeline> element
current Docs at  [Timeline Horizontal](https://www.flowbite-react.com/docs/components/timeline#horizontal-timeline)
**and below is the Current proposed fix in Docs**

docs(examples/../timeline.horizontal.tsx): timeline Horizontal was missing the horizontal boolean value

---

src/components/Navbar/NavbarCollapse.tsx
src/components/Navbar/NavbarLink.tsx

When we go to the Mobile Screen and when we click on Navbar, it opens the Collapse, and when we click on any of the Link and it get redirected to another page, but Navbar Collapse isn't getting closed, it was only getting closed from Navbar Toggle nowhere else.
This fix is adding the onClick event to NavbarCollapse so whenever we click on the Link, it is closing the navbar.
**Current:**
**Fixed:**

fix(navbar): on Mobile Screen Navbar remains open even page is changed

---

src/components/Button/ButtonGroup.tsx

Dynamically generated buttons within a button group are not properly styled. 
fix #1269

fix(ButtonGroup): dynamic generated button with group wasn't styled properly

---

package.json
src/components/Carousel/Carousel.tsx
src/helpers/drag-scroll/index.tsx
styles/globals.css
yarn.lock

Users of flowbite-react with a strict CSP will not permit inline styles. In order to whitelist inline styles in a CSP, you must add the `unsafe-inline` value to the `style-src` directive. Allowing inline styles opens the application up to cross-site scripting attacks (XSS). 
The `<Carousel>` component in flowbite-react indirectly introduces inline styles via the `react-indiana-drag-scroll` library, which [inlines all of its styles via the build process](https://github.com/Norserium/react-indiana-drag-scroll/blob/6b76dcbddfcbc69a48411f91f68f266901e24694/rollup.config.js#L35).
I considered updating react-indiana-drag-scroll's build config to avoid inlining the styles, but that would introduce a signifiant breaking change for all other users of the library. So, given the small size of the …

Fix CSP violation in Carousel drag-scroll helper

---

src/components/Modal/theme.ts

Modal overflowing the bottom in chrome on ios due to not using dynamic viewport units.
I fixed this problem in my personal project by changing the inner prop of modal's theme. This [answer](https://stackoverflow.com/a/77490743) helped me.
| Current | Fixed |
|--------|--------|
| ![IMG_3639](https://github.com/themesberg/flowbite-react/assets/9607568/4f905f42-7a55-4019-a725-fbee4c1183b6) | ![IMG_3638](https://github.com/themesberg/flowbite-react/assets/9607568/8355bfa2-15f3-4279-8fef-927dc733bb65) |

fix(modal): modal overflowing bottom in chrome on ios

---

apps/web/examples/popover/popover.image.tsx
apps/web/examples/popover/popover.password.tsx

docs(popover) - fix svg path JSX format

---

.changeset/quiet-camels-bake.md
packages/ui/src/components/Timeline/Timeline.spec.tsx
packages/ui/src/components/Timeline/TimelineContent.tsx
packages/ui/src/components/Timeline/theme.ts

This is a port of #1224 PR to the new monorepo structure, thanks @revuwem!
The theme now supports optional `root.vertical` and `root.horizontal` props.

fix(ui): timeline - content - separate base styles from horizontal/vertical

---

.changeset/petite-toys-fold.md
apps/web/content/docs/customize/config.mdx
packages/ui/scripts/generate-metadata.ts

fix(schema): include `dark`

---

.changeset/short-candies-warn.md
apps/web/next.config.mjs
packages/ui/src/cli/commands/dev.ts
packages/ui/src/plugin/nextjs.ts

Fix `nextjs` plugin to work on all environments
- fix(ui): `nextjs` plugin to run properly on `NODE_ENV` environments: `production`, `development` and `test`
- log file writes in `dev`
`withFlowbiteReact` now always returns async configuration (see: [Async Configuration](https://nextjs.org/docs/app/api-reference/config/next-config-js#async-configuration)) so make sure to wrap any other HOC (higher-order-functions) such as `withContentlayer` because most of them do not forward pass async config arguments (eg: `phase, options`)
```tsx
// ❌ not working
export default withContentlayer(withFlowbiteReact(nextConfig));
// ✅ working
export default withFlowbiteReact(withContentlayer(nextConfig));
```

Fix `nextjs` plugin to work on all environments
