- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This PR adds:
- Code of Conduct
- Contributing Guide
> Contributing guide and Code of Conduct

- public/images/tables-dark.svg
- public/images/tables-light.svg
- src/components/Table/Table.stories.tsx
- src/components/Table/TableBody.tsx
- src/components/Table/TableCell.tsx
- src/components/Table/TableContext.tsx
- src/components/Table/TableHead.tsx
- src/components/Table/TableHeadCell.tsx
- src/components/Table/TableRow.tsx
- src/components/Table/index.tsx
- src/components/index.ts
- src/pages/TablePage.tsx
- src/routes.tsx
> Add Table component

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/FormControls/Checkbox.stories.tsx
- src/components/FormControls/FileInput.stories.tsx
- src/components/FormControls/Label.stories.tsx
- src/components/FormControls/Radio.stories.tsx
- src/components/FormControls/Select.stories.tsx
- src/components/FormControls/TexInput.stories.tsx
- src/components/FormControls/Textarea.stories.tsx
- src/components/FormControls/ToggleSwitch.stories.tsx
> Component stories

- .storybook/main.js
- package.json
- yarn.lock
This PR adds the accessibility checker to storybook.
> chore: add accessibility check to storybook

- src/components/Alert/Alert.stories.tsx
adding more story types to the alert component
> chore: alert stories

- src/components/Badge/Badge.stories.tsx
adding more story types to the badge component
> chore: badge stories

- src/Root.tsx
- src/components/Badge/index.tsx
- src/components/Button/index.tsx
- src/components/Sidebar/SidebarCTA.tsx
- src/components/Sidebar/SidebarCollapse.tsx
- src/components/Sidebar/SidebarItem.tsx
- src/components/Sidebar/SidebarItemGroup.tsx
- src/components/Sidebar/SidebarItems.tsx
- src/components/Sidebar/SidebarLogo.tsx
- src/components/Sidebar/index.tsx
- src/helpers/childrenAsArray.ts
- src/routes.tsx
Refactors the `Sidebar` component into a compound component.
This is a dramatic API change. `Sidebar`s used to be constructed like so:
```js
<Sidebar
collapsed={false}
itemsGroups={[
[
{
group: false,
href: '#',
icon: HiChartPie,
title: 'Dashboard'
},
{
group: false,
href: '#',
icon: HiViewBoards,
label: 'Pro',
title: 'Kanban'
},
{
group: false,
href: '#',
icon: HiInbox,
label: '3',
title: 'Inbox'
},
{
group: false,
href: '#',
icon: HiUser,
title: 'Users'
},
{
group: false,
href: '#',
icon: HiShoppingBag,
title: 'Products'
},
{
group: false,
href: '#',
icon: HiArrowSmRight,
title: 'Sign In'
},
{
group: false,
href: '#',
icon: HiTable,
title: 'Sign Up'
}
]
]}
/>
```
They now look like this:
```js
<Sidebar>
<Sidebar.Items>
<Sidebar.ItemGroup>
<Sidebar.Item href="#" icon={HiChartPie}> …
```
> refactor(component): Rewrite `Sidebar` as a compound component

- README.md
This is a first draft for a README.
> chore(docs): Add `README`

- package.json
- src/lib/components/Sidebar/Sidebar.spec.tsx
- src/lib/components/Tooltip/Tooltip.spec.tsx
- src/lib/components/Tooltip/Tooltip.stories.tsx
- src/lib/components/Tooltip/index.tsx
- src/setupTests.js
- yarn.lock
> Add unit tests for `Tooltip`s

- package.json
- src/lib/components/Sidebar/Sidebar.spec.tsx
- src/lib/components/Sidebar/SidebarItem.tsx
> Remove `react-router-dom` peer dependency

- src/docs/pages/AlertsPage.tsx
- src/docs/pages/ThemePage.tsx
- src/lib/components/Alert/Alert.spec.tsx
- src/lib/components/Alert/Alert.stories.tsx
- src/lib/components/Alert/index.tsx
> test(component): Add unit tests for Alert, resolves #44 

- src/docs/pages/RatingPage.tsx
- src/lib/components/Alert/Alert.spec.tsx
- src/lib/components/Rating/Rating.spec.tsx
- src/lib/components/Rating/Rating.stories.tsx
- src/lib/components/Rating/RatingAdvanced.tsx
- src/lib/components/Rating/RatingStar.tsx
> test(component): Add unit tests for Ratings, resolves #43

- src/lib/components/Badge/Badge.spec.tsx
- src/lib/components/Badge/Badge.stories.tsx
- src/lib/components/Badge/index.tsx
> test(component): Add unit tests for `Badge`s, resolves #45

- src/docs/pages/AvatarPage.tsx
- src/docs/pages/NavbarPage.tsx
- src/lib/components/Alert/Alert.spec.tsx
- src/lib/components/Navbar/Navbar.spec.tsx
- src/lib/components/Navbar/Navbar.stories.tsx
- src/lib/components/Navbar/NavbarCollapse.tsx
- src/lib/components/Navbar/NavbarToggle.tsx
> test(component): Add unit tests for `Navbar`s, resolves #41

- src/lib/components/DarkThemeToggle/DarkThemeToggle.spec.tsx
- src/lib/components/DarkThemeToggle/index.tsx
> test(component): Add unit tests for `DarkThemeToggle`

- src/docs/pages/SpinnersPage.tsx
- src/lib/components/Spinner/Spinner.spec.tsx
- src/lib/components/Spinner/Spinner.stories.tsx
- src/lib/components/Spinner/index.tsx
> test(component): Add unit tests for `Spinner`s

- src/docs/pages/DashboardPage.tsx
- src/lib/helpers/index.ts
- src/lib/helpers/mergeDeep.spec.ts
- src/lib/helpers/range.spec.ts
- src/lib/helpers/range.ts
- src/lib/index.ts
> test(helper): Add unit tests for helpers, resolves #108

- src/lib/components/Modal/Modal.spec.tsx
- src/lib/components/Modal/Modal.stories.tsx
- src/lib/components/Modal/index.tsx
> test(component): Add unit tests for `Modal`s

- src/lib/components/Dropdown/Dropdown.spec.tsx
- src/lib/components/Dropdown/Dropdown.stories.tsx
> test(component): Add unit tests for `Dropdown`, resolves #37

- package.json
- src/docs/pages/TabsPage.tsx
- src/lib/components/Tab/Tabs.spec.tsx
- src/lib/components/Tab/Tabs.stories.tsx
- src/lib/components/Tab/index.tsx
- yarn.lock
> feature(component): Add keyboard support to `Tabs`

- src/docs/pages/AvatarPage.tsx
- src/lib/components/Avatar/Avatar.spec.tsx
- src/lib/components/Avatar/AvatarGroup.tsx
- src/lib/components/Avatar/index.tsx
- src/lib/components/Button/Button.spec.tsx
> Avatar unit test

- src/lib/components/Card/Card.spec.tsx
- src/lib/components/Card/index.tsx
> test(component):Add unit test for 'Card' 

- src/lib/components/Progress/Progress.spec.tsx
- src/lib/components/Progress/Progress.stories.tsx
- src/lib/components/Progress/index.tsx
> test(component): Add unit tests for `Progress`, resolves #42

- src/lib/components/Footer/Footer.spec.tsx
- src/lib/components/Footer/index.tsx
> test(component):Add unit test for 'Footer'

- src/docs/pages/ThemePage.tsx
- src/lib/components/Avatar/Avatar.spec.tsx
- src/lib/components/Avatar/index.tsx
- src/lib/components/Flowbite/FlowbiteTheme.d.ts
- src/lib/components/Flowbite/index.tsx
- src/lib/helpers/deep-partial.d.ts
- src/lib/helpers/exclude.spec.ts
- src/lib/helpers/exclude.ts
- src/lib/theme/default.ts
`Avatar`s can now be customized using `<Flowbite theme={..}>`.
`avatar.size` will also respect any additional sizes you would like to create. For example, `<Avatar size="xxl" .../>`.
```js
avatar: {
base: 'flex items-center space-x-4',
bordered: 'p-1 ring-2 ring-gray-300 dark:ring-gray-500',
img: {
disabled: 'rounded relative overflow-hidden bg-gray-100 dark:bg-gray-600',
enabled: 'rounded',
},
rounded: '!rounded-full',
size: {
xs: 'w-6 h-6',
sm: 'w-8 h-8',
md: 'w-10 h-10',
lg: 'w-20 h-20',
xl: 'w-36 h-36',
},
stacked: 'ring-2 ring-gray-300 dark:ring-gray-500',
status: {
away: 'bg-yellow-400',
base: 'absolute h-3.5 w-3.5 rounded-full border-2 border-white dark:border-gray-800',
busy: 'bg-red-400',
offline: 'bg-gray-400',
online: 'bg-green-400',
},
statusPosition: {
'bottom-left': …
```
> feature(component): Rewrite `Avatar` to use themes, resolves #127

- src/lib/components/Badge/index.tsx
- src/lib/components/Button/index.tsx
- src/lib/components/Flowbite/FlowbiteTheme.ts
> fix(type): Generate `FlowbiteTheme.d.ts` to builds

- src/docs/pages/ToastPage.tsx
- src/lib/components/Flowbite/FlowbiteTheme.ts
- src/lib/components/Toast/ToastToggle.tsx
- src/lib/components/Toast/index.tsx
- src/lib/theme/default.ts
**Toast** can be customized using  **< Flowbite theme={..} >**
```ts
toast: {
base: string;
closed: string;
removed: string;
toggle: {
base: string;
icon: string;
};
};
```
closes #146
> feat(component): theme support to toast

- src/lib/components/FormControls/TextInput.tsx
> fix(component): add forwardRef to TextInput

- src/lib/components/Flowbite/FlowbiteTheme.ts
- src/lib/components/Progress/Progress.stories.tsx
- src/lib/components/Progress/index.tsx
- src/lib/theme/default.ts
**Progress** can be customized using  **< Flowbite theme={..} >**
```
progress: {
base: string;
label: string;
bar: string;
color: string;
size: string;
};
```
> feature(component): Rewrite Progress to use themes, resolves #141

- src/lib/theme/default.ts
I have changed the css values from "common" px values to arbitrary values like "rem".
> fixed min-h to arbitrary values (rem)

- CONTRIBUTING.md
- package.json
- yarn.lock
Adds a new tool to all seat belt to help us to make better commit messages.
https://commitizen-tools.github.io/
Making official what @mouracamila started on #135 
None.
N/A
N/A
> chore: makes the repository commitizen friendly

- .editorconfig
- package.json
- src/docs/pages/FooterPage.tsx
- src/lib/components/Flowbite/FlowbiteTheme.ts
- src/lib/components/Footer/Footer.spec copy.tsx
- src/lib/components/Footer/Footer.spec.tsx
- src/lib/components/Footer/Footer.stories.tsx
- src/lib/components/Footer/FooterBrand.tsx
- src/lib/components/Footer/FooterCopyright.tsx
- src/lib/components/Footer/FooterDivider.tsx
- src/lib/components/Footer/FooterIcon.tsx
- src/lib/components/Footer/FooterLink.tsx
- src/lib/components/Footer/FooterLinkGroup.tsx
- src/lib/components/Footer/FooterTitle.tsx
- src/lib/components/Footer/index.tsx
- src/lib/theme/default.ts
- yarn.lock
Rewrite the component footer to accept theme.
Fixes #177 
- Some structural changes to the Footer layout.
- Removes the direct access to `className` to all footer components
- Adds the theme support to the component
```
footer: {
base: string;
col: string;
container: string;
bgDark: string;
groupLink: {
base: string;
link: {
base: string;
href: string;
};
col: string;
};
icon: {
base: string;
size: string;
};
title: {
base: string;
};
divider: {
base: string;
};
copyright: {
base: string;
href: string;
span: string;
};
brand: {
base: string;
img: string;
span: string;
};
};
```
- The page loaded and there was no error in the console
> refactor(footer): Adds the theme support to footer component 

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: better bug template

- src/lib/components/Carousel/index.tsx
- src/lib/components/Flowbite/FlowbiteTheme.ts
- src/lib/theme/default.ts
Please include a summary of the change and which issue is fixed. Please also have relevant motivation and context. List any dependencies that are required for this change.
- N/A
> refactor(carousel): extends the theme to control element

- src/docs/pages/DropdownPage.tsx
- src/lib/components/Dropdown/DropdownDivider.tsx
- src/lib/components/Dropdown/DropdownHeader.tsx
- src/lib/components/Dropdown/DropdownItem.tsx
- src/lib/components/Dropdown/index.tsx
- src/lib/components/Floating/index.tsx
- src/lib/components/Flowbite/FlowbiteTheme.ts
- src/lib/theme/default.ts
- Hardware:
- Toolchain:
- SDK:
> Moved dropdown classes to flowbite theme

- src/lib/components/Navbar/Navbar.stories.tsx
- src/lib/theme/default.ts
This should be optional as a prop in the component or just wrap the toggle in a div.
Having this as a default makes it difficult to
Change it.
- Hardware:
- Toolchain:
- SDK:
> Removes the default margin-left on Navbar.Toggle

- src/lib/components/Pagination/index.tsx
The wrong class was referenced, copy-paste issues probably.
Fixes #330 
None
Visually
> fix(pagination): fix next button icon misalignment

- public/index.html
meta description tag changed from Web site created using create-react-app to Build websites even faster with components on top of React and Tailwind CSS
> update meta description tag

- src/lib/theme/default.ts
Avatar wasn't horizontally centered and it was causing issues.
No.
N/A
> fix(avatar): center avatar correctly

- src/lib/components/Sidebar/Sidebar.tsx
- src/lib/components/Sidebar/SidebarLogo.tsx
- src/lib/components/Tab/TabItem.tsx
- src/lib/components/Tab/Tabs.tsx
More components with access to `className`
No.
N/A
> feat(classname): more missing classnames access

- docs/content/components/badge.md
Moves the `Badge` component documentation to Hugo. Also, added and updated the Usage, Properties, and Example sections in the documentation as specified in the Issue.
Fixes #275 
N/A
N/A
> docs: migrate the badge docs to hugo

- src/lib/components/Sidebar/SidebarItem.tsx
Added forwardRef to sidebar item to support Next link
fix #397
> feat(sidebaritem): add forwardRef to sidebar item

- src/lib/components/Breadcrumb/BreadcrumbItem.tsx
Added forwardRef to breadcrumb item to support Next link
> feat(breadcrumbitem): add forwardRef to breadcrumb item

- docs/content/components/button-group.md
- docs/content/components/buttons.md
Moves the `Button` and `ButtonGroup` component documentation to Hugo. Also, added and updated the Usage, Properties, and Example sections in the documentation as specified in the Issue.
Fixes #277 
N/A
N/A
> docs: migrate the button to hugo

- .github/FUNDING.yml
> chore(sponsor): add tulup-conner

- src/lib/components/Carousel/Carousel.spec.tsx
- src/lib/components/Carousel/Carousel.tsx
#49
Adds test cases for the `src/lib/components/Carousel/Carousel.tsx` component.
Tests have shown that the component does not handle the error if slides were not provided. (Fixed)
The component logic was updated a bit according to test results.
Fixes #49
> test(carousel): adds test cases for the carousel component

- src/lib/components/Checkbox/Checkbox.tsx
- src/lib/components/FileInput/FileInput.tsx
- src/lib/components/Navbar/Navbar.tsx
- src/lib/components/Navbar/NavbarBrand.tsx
- src/lib/components/Navbar/NavbarCollapse.tsx
- src/lib/components/Navbar/NavbarLink.tsx
- src/lib/components/Navbar/NavbarToggle.tsx
- src/lib/components/Radio/Radio.tsx
- src/lib/components/TextInput/TextInput.tsx
- src/lib/components/ToggleSwitch/ToggleSwitch.tsx
- src/lib/theme/default.ts
Adds `theme` prop support for the following components:
> feat: add theme prop

- src/lib/components/TextInput/TextInput.tsx
Quick hotfix to solve bad merge :)
> fix(textinput): merge issue

- src/lib/components/Sidebar/SidebarItem.tsx
This PR fixes the `next/link` component for the `SidebarItem`.
Fixes #430
> fix(sidebaritem): fix sidebar item with next link

- src/docs/pages/AccordionPage.tsx
- src/lib/components/Accordion/Accordion.tsx
Added `collapseAll` prop to resolve #515 
- Hardware:
- Toolchain:
- SDK:
> feat(accordion): add collapseAll prop (#515)

- src/docs/pages/ModalPage.tsx
- src/lib/components/Modal/Modal.spec.tsx
- src/lib/components/Modal/Modal.tsx
- src/lib/hooks/index.ts
- src/lib/hooks/useKeyDown.ts
Added `dismissible` prop to resolve #497 
- Hardware:
- Toolchain:
- SDK:
> Feat dismissible modal

- src/docs/pages/NavbarPage.tsx
- src/lib/components/Navbar/NavbarBrand.tsx
- src/lib/components/Navbar/NavbarLink.tsx
added `as` prop to resolve #526 
- Hardware:
- Toolchain:
- SDK:
> feat(Navbar): add as prop (#526)

- src/docs/pages/FormsPage.tsx
update forms doc to resolve #485 
- Hardware:
- Toolchain:
- SDK:
> docs(Form): add input colors (#485)

- src/lib/theme/default.ts
Solve border radius issue on safari browser 
Fixes #496 
- Hardware:
- Toolchain:
- SDK:
> style(FileInput): fix border radius on safari #(496)

- src/lib/theme/default.ts
Update the border-radius class from `rounded` to `rounded-lg` to match the core Flowbite library.
Related to #575 
- Hardware:
- Toolchain:
- SDK:
> style(Dropdown): update border radius from rounded to rounded-lg #(575)

- docs/content/components/button-group.md
- src/docs/pages/AccordionPage.tsx
- src/docs/pages/ButtonGroupPage.tsx
- src/docs/pages/FormsPage.tsx
- src/docs/pages/ModalPage.tsx
- src/lib/components/Accordion/Accordion.stories.tsx
- src/lib/components/Modal/Modal.stories.tsx
> fix(/docs): remove `{' '}` literals from code examples

- src/lib/components/Badge/Badge.stories.tsx
- src/lib/components/Badge/Badge.tsx
- src/lib/theme/default.ts
This change starts adding all colors to components in Flowbite. I'll be partially updating the components until I got every of then with all colors from FlowbiteColors avaliable. 
Fixes # [473](https://github.com/themesberg/flowbite-react/issues/473) _(partially)_
Since it was a visual change I used the Storybook to validate if colors are changing as expected.
> feat(/lib/theme): add Tailwind CSS colors to  `<Badge>`s

- LICENSE
- README.md
This PR updates the `LICENSE.md` file to Bergside Inc. and also adds a link to the brand usage guidelines to the README file.
We will, however, mention that @bacali95 was the original author of the package for proper credits.
No test required, it's just the LICENSE and README `.md` files.
Not required.
> chore(readme): brand guideline and license

- src/lib/components/Checkbox/Checkbox.tsx
- src/lib/components/FileInput/FileInput.tsx
- src/lib/components/Radio/Radio.tsx
- src/lib/components/RangeSlider/RangeSlider.tsx
- src/lib/components/Select/Select.tsx
displayName property added for Checkbox, FileInput, Radio, RangeSlider, and Select components
Fixes #641 
> docs(component): displayName property added for components on Forms page

- src/lib/theme/default.ts
Fixes 
While keeping the `<ul><li>` elements in-tact.
Also see https://flowbite-react.com/list-group
After
N/A
> fix: group list styling

- src/lib/theme/default.ts
Fixes #600 
Additional fix as per https://github.com/themesberg/flowbite-react/issues/600#issuecomment-1504547360
> Prevent modals from being truncated at the top

- src/lib/components/Modal/Modal.tsx
> fix(component/models): prevent scrolling of body when modal is shown

- src/lib/components/Button/Button.tsx
Fixes # 663
- Hardware:
- Toolchain:
- SDK:
> fix(button.tsx): make prop theme work

- src/lib/theme/default.ts
#537
- Hardware:
- Toolchain:
- SDK:
> fix(modal): overflow bug fix

- app/components/fathom.tsx
- app/layout.tsx
- package.json
- yarn.lock
Add Fathom Analytics to Flowbite React.
Fixes # [(issue)](https://github.com/themesberg/flowbite-react/issues/782)
No test required.
> docs(fathom): add fathom analytics

- app/components/fathom.tsx
Fix Fathom Analytics user visit registration by removing an attribute
> docs(fathom): remove includedDomains attribute

- app/components/navbar.tsx
It updates the documentation to display the latest version for `package.json` at the navbar.
None.
I just run it, and check if it was working.
Not relevant.
> docs: version from package.json

- src/components/Pagination/PaginationButton.tsx
Button now has a type button to prevent page to refresh
fix #809
Button now has type button to prevent page to refresg
Fixes # (809)
- Hardware:
- Toolchain:
- SDK:
> fix(paginationbutton.tsx): button now has type button

- CONTRIBUTING.md
- README.md
- app/docs/getting-started/contributing/contributing.mdx
> docs: update README, CONTRIBUTING

- app/docs/components/modal/index.tsx
- app/docs/components/modal/modal.mdx
- src/components/Modal/Modal.spec.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/ModalContext.tsx
- src/components/Modal/ModalHeader.tsx
This PR implements the Modal accessibility rules leveraging the floating-ui hooks and components
Fix #647 Fix #701 #841
> feat(modal.tsx): Modal Accessibility

- app/docs/components/modal/modal.mdx
This PR fixes a small typo in the Modal documentation.
> fix(modal.mdx): fix spelling in modal documentation

- README.md
- Issue #903 
edit contributing guide link in README.md file
Fixes #903
> docs(readme): edit contributing guide link

- app/components/carbon-ads.tsx
- app/components/navbar.tsx
- app/docs.css
- app/docs/layout.tsx
- app/layout.tsx
- app/page.tsx
- package.json
- yarn.lock
I've integrated the Algolia DocSearch functionality and made some smaller improvements to the hero section.
> Added search functionality to docs

- app/docs.css
- app/docs/layout.tsx
- app/page.tsx
This PR attempts to fix the Algolia Search styles and also slightly updates the homepage navbar height.
> docs: allow mobile users to close search

- app/docs/components/toast/toast.mdx
> docs: added missing external imports for Toast Component

- README.md
> docs: readme docs update link + add new components (banner + datepicker)

- src/components/Breadcrumb/Breadcrumb.stories.tsx
> docs: Add missing controls to Breadcrumbs component StoryBook

- app/docs/components/spinner/spinner.mdx
- app/docs/components/toast/toast.mdx
- src/components/Breadcrumb/theme.ts
- src/components/Button/theme.ts
- src/components/ListGroup/theme.ts
I've fixed the following visual bugs:
- align text and icons by default vertically inside buttons
- make the chevron icon smaller for the breadcrumb component
- list group icon and text vertical alignment
- resize spinner icon inside the button examples
- align buttons inside the toast component
> Minor visual fixes for components (buttons, breadcrumbs, list group)

- README.md
Adding the flowbite package to "npm i" as in yarn. In my opinion it should be there if we use "flowbite/plugin" below.
> docs: add flowbite to npm install

- src/components/Banner/Banner.stories.tsx
> docs: add default sticky banner example to StoryBook

- CONTRIBUTING.md
- app/docs/getting-started/contributing/contributing.mdx
> docs: remove contributing yarn format for prettier:fix

- app/data/components.tsx
- app/docs/layout.tsx
- public/images/components/floating-label.svg
> fix: documentation regressions

- app/docs/forms/floating-label/floating-label.mdx
- app/docs/forms/floating-label/page.tsx
Add Floating  Label theme and flowbite reference to match other components
> docs: floating Label add missing theme and references

- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/theme.ts
> feat: checkbox colors

- app/docs/customize/theme/theme.mdx
[X] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)
Attributes (like color in the example) must be set when using a custom theme on a component.
Documentation wasn't working out of the box.
Reference related issues using # followed by the issue number.
No issue created
No API change
> docs: set color with custom theme

- app/docs/layout.tsx
> I found a typo in the documentation. The new component `KBD` was listed as `KDB` in the documentation menu
> N/A
> Fixed typo - Correcting menu item "KDB" to "KBD"

- examples/toast/toast.colors.tsx
- examples/toast/toast.customDismissal.tsx
- examples/toast/toast.feedback.tsx
- examples/toast/toast.interactive.tsx
- examples/toast/toast.root.tsx
- examples/toast/toast.withButton.tsx
> fix docs toast examples `githubSlug`

- app/docs/[[...slug]]/page.tsx
- app/docs/layout.tsx
- components/homepage/components-section.tsx
- data/components.tsx
- data/docs-sidebar.ts
https://github.com/themesberg/flowbite-react/assets/41998826/7a47063d-9267-4b93-a327-a841fb4a0c0e
> Docs: cleanup + pager

- content/docs/components/tabs.mdx
> docs(tabs): fix tabs theme typo tabs->tab #1123

- examples/progress/progress.colors.tsx
- src/components/Progress/Progress.tsx
- src/components/Progress/theme.ts
- Added missing colors to Progress Bar
- Blue != Cyan
> feat(progress): add missing colors for Progress component

- examples/listGroup/listGroup.root.tsx
- src/components/ListGroup/ListGroupItem.tsx
- src/components/ListGroup/theme.ts
> Fix: listItem disabled property

- src/components/Carousel/Carousel.tsx
- src/components/Carousel/theme.ts
Edited the Carousel.tsx to add the option to disable the mouse drag of the carousel component
Discussion (https://github.com/themesberg/flowbite-react/discussions/1120)
Optional Prop "draggable":boolean for carousel component.
> Added draggable option to carousel component

- content/docs/getting-started/introduction.mdx
Performance optimisation can be applied to tailwind config content path towards `react-flowbite`, less files to analize = faster compile times.
Today we have an issue of big compile time due to website packages not being separated by the lib packages. This PR solves that.
Before (86s)
After (859ms)
> (docs) introduction: fix tailwind config step

- examples/tabs/tabs.fullWidth.tsx
Before
https://github.com/themesberg/flowbite-react/assets/41998826/6ec9301f-bb87-44af-844c-3c4caa9dd7fa
After
https://github.com/themesberg/flowbite-react/assets/41998826/785748b6-6e6f-4651-b320-f2200982646b
> docs(tabs): fix page overflow

- examples/table/table.hover.tsx
- examples/table/table.root.tsx
- examples/table/table.striped.tsx
- examples/table/table.withCheckboxes.tsx
Before
https://github.com/themesberg/flowbite-react/assets/41998826/faf14fdb-ca62-488d-b0c0-41d0585a38fa
After
https://github.com/themesberg/flowbite-react/assets/41998826/772aad92-5c3b-4a5b-a9f0-abc28b25511f
> docs(table): fix page overflow

- src/components/Banner/Banner.spec.tsx
- src/components/Datepicker/Datepicker.spec.tsx
- src/components/ThemeModeScript/ThemeModeScript.spec.tsx
- vitest.config.ts
Adds unit tests for various components that need them. Should increase coverage sufficiently to pass Codecov's 95% threshold for CI/CD checks to complete successfully.
No breaking changes!
> test: add missing unit tests

- src/components/List/List.stories.tsx
Add list horizontal stories
There are no breaking API changes.
> feat(list.stories.tsx): add horizontal stories

- content/docs/getting-started/nextjs.mdx
Leave a note about older versions for users running them.
resolve #1158
> docs: update Getting Started->Next.js for Next 13+

- app/docs/[[...slug]]/page.tsx
- components/homepage/main-footer.tsx
- content/docs/getting-started/license.mdx
- src/components/Datepicker/helpers.spec.tsx
New year, new resolution 😎
Footer
> Update with new year (2024)

- src/components/Alert/theme.ts
Exactly like PR #1227, but for Alert component.
Modified the color of the alerts from cyan to a blue color
> fix(alert): blue color on alert is cyan

- examples/fileInput/fileInput.dropzone.tsx
> fix: typo in fileInput.dropzone.tsx
